.travis.yml

Send report to CodeCov after successful build.

CI: Send report to codecov after success

---

.travis.yml

Change IF statement before `doctr deploy` is executed

CI: Make sure docs are deployed

---

docs/source/basic_usage.rst
typhon/display.py

Noted these issues while poking around on a local installation. Worked quite well otherwise!
I'll send along more details on my little example later, as I think you'll find it interesting.

FIX: docs and sub-Devices in DeviceDisplay

---

tests/conftest.py
tests/test_display.py
tests/test_plot.py
typhon/display.py
typhon/plot.py
typhon/ui/plot.ui
typhon/ui/plotitem.ui
typhon/utils.py

Add a plotting tool that can be configured live with signals from the device. 
Closes #60 
Full test suite for all methods

ENH: Plot Tool

---

tests/conftest.py

Establish connections on widgets before showing them to the user. Necessary after https://github.com/slaclab/pydm/pull/346

DEV: Establish connections on shown widgets

---

dev-requirements.txt
tests/test_console.py
tests/test_display.py
tests/test_func.py
tests/test_log.py
tests/test_plot.py
tests/test_plugins.py
tests/test_signal.py
tests/test_utils.py
typhon/utils.py

Add `qtbot` to all tests where widgets are created.
I hate segfaults, you hate segfaults, we all hate segfaults

TST: Qtbot

---

tests/test_plugins.py
tests/test_signal.py
typhon/plugins/core.py

After https://github.com/slaclab/pydm/pull/355, `PyDMChannel` will connect itself.  This caused some issues not in the code itself, but the testing suite where we monkeyed around connecting signals to plugins itself. Also was adding some `print` statements to discombobulate what was going on and realized that some more logging messages would be helpful. 😄

TST: SignalConnection 

---

requirements.txt
setup.py

DEV: use install_requires in setup.py

---

bin/typhon_env.sh

Slight error in `typhon_env.sh` script from #130

FIX: Point to bin folder not typhon source

---

.travis.yml

Python 3.7

---

.travis.yml
pytest.ini

CI: clean usage of apt-get

---

tests/conftest.py
tests/test_positioner.py
tests/test_signal.py

TST: remove fake epics pv

---

typhon/status.py

Sent errors from the status thread to the error logger
Uncaught exceptions in this thread segfault the GUI
It really hasn't been tested enough, just throwing this up for now

FIX: log the status errors

---

tests/test_console.py

One last little bit of `QtConsole` cleanup in the test suite.

FIX: Cleanup after TyphonConsole

---

docs/source/basic_usage.rst

DOC: update basic_usage.rst

---

MANIFEST.in
setup.py

Closes #231 
- FIX: Add requirements.txt to MANIFEST.in.
- FIX: Only display manual install message if we have packages for that condition.
- pip install of package was broken. See #231 
- tested locally
- N/A

Package Adjustments

---

tests/test_utils.py
typhos/utils.py

TST: Add tests for typhos.utils.no_device_lazy_load.
It makes more sense for this function to live here.

REF: Move no_device_lazy_load from lucid to typhos.

---

.gitignore
tests/conftest.py

Closes #127 
Would like to get these artifacts uploaded somewhere eventually, but I think this is sufficient to close the issue for now.

TST: save images

---

tests/conftest.py
tests/test_cli.py
tests/test_log.py
tests/test_suite.py
typhos/suite.py
typhos/tools/log.py

Retractable suite which can be pinned:

ENH: add the QPopBar for the suite from pcdsutils.qt

---

tests/test_utils.py
typhos/utils.py

REF: use raise_to_operator from pydm

---

typhos/display.py
typhos/panel.py

Provide option to hide empty panels.
Closes #278 
Supersedes #280
Discussion at PR #278 
Locally
They will come tomorrow.

ENH: Add hide empty panels functionality.

---

tests/plugins/test_happi.py
tests/test_display.py
tests/test_panel.py
typhos/cache.py
typhos/display.py
typhos/panel.py
typhos/plugins/happi.py
typhos/suite.py
typhos/tools/plot.py

REF/FIX: use Qt.QueuedConnection for signal connections

---

tests/test_cache.py

Pulled from #290 
~Review/merge #294 before this one~

TST: add simple cache tests

---

typhos/display.py

Single line is failing all of our builds, and I've fixed this in several PRs now. Let's just do it once here.

STY: flake8 strictness

---

tests/test_cache.py

Need to reproduce and address cache race conditions discovered in #291.
Eventually will close #295

TST: remove cache test skip

---

etc/typhos_designer_plugin.py
typhos/designer.py

Minor tweaks as I poke around with the designer.
Closes #299 - verified locally that the designer is working.

MNT: note available data plugins

---

docs/source/index.rst
docs/source/release_notes.rst

Add release notes to documentation

DOC: add release notes document based on github releases

---

docs/source/display.rst
docs/source/release_notes.rst
docs/source/utils.rst

Add release notes for v0.8.0
Anything I'm missing?

DOC: add release notes for v1.0.0

---

.travis.yml
conda-recipe/build.sh
conda-recipe/meta.yaml

- conda-recipe
Updates to be in sync with conda-forge and fixes for the expansion of the environment variables at the designer plugins.
- .travis.yml
Switches the file to use the new pcds-ci-helpers.
Closes https://github.com/pcdshub/typhos/issues/334
https://github.com/pcdshub/pcds-ci-helpers/pull/31. Once the mentioned PR is merged we can remove the hardcoded piece here pointing to my fork and branch.
Simplify and have a consistent and uniform CI process.
CI
N/A

BLD & CI: Update conda-recipe and update CI to use shared-configs.

---

typhos/positioner.py

Fix issue where default timeout of 10s from `typhos.status` was being used above the timeout decided by the positioner widget.
#352 didn't quite work
The status monitor has its own timeout separate from the move status's timeout.
This PR opts to only use the status monitor timeout because if we use the move status timeout the motion is stopped in event of an errant timeout.
Locally with "real" fake motors (test Beckhoff motion IOC with simulated axes)

MNT: timeout follow-up

---

docs/source/release_notes.rst

Contains contributions from Ken, Hugo, and myself

DOC: add release notes for v1.0.2

---

typhos/widgets.py

The kwarg in this method chain is dropped. This PR picks it back up.
This code path is used in lightpath.
Lightpath loads more things now.

MNT: pass down kwarg correctly

---

typhos/cli.py

Addresses #373 but we may want to look further into it before closing

FIX: numbers in class names

---

typhos/cli.py

Fixes the previous one-line PR

FIX: fix the fixed regex

---

typhos/benchmark/cases.py

Make the depth test less deep to maybe avoid recursion depth error
The benchmark is useless if it doesn't complete
Failing tests are annoying

MNT: fix benchmark tests

---

MANIFEST.in

ui files moved in a recent PR, the manifest needs to be adjusted
the as-built package is not shipped with the ui files
local conda build

BLD: include new ui file location in manifest

---

docs/source/release_notes.rst

DOC: v1.1.1 release notes

---

typhos/utils.py

`ophyd.signal.SignalRO` is another read-only signal variant that is not currently checked in typhos.
Rather than adding that class to the list of classes to check in addition to our own `SignalRO`, this PR makes those two classes one in the same - if available in ophyd, of course.
Closes #411 
Test suite which leverages the built-in `SignalRO` continues to work locally.
Before:
After:
n/a

FIX: add ophyd.signal.SignalRO to the list of read-only classes

---

docs/source/release_notes.rst

DOC: write release notes for adding at1k4

---

docs/source/release_notes.rst

I want to tag the recent fixes and additions to the library

DOC: write release notes for v1.2.0

---

typhos/display.py

Open docs in a new window, without resorting to opening in a browser.
We are currently hopeful the built-in documentation will be of general use.
However, our screens generally have an aspect ratio that's taller than it is wide, which is poor for viewing Confluence.
Looking at the screenshot below, you can easily pop out the help documentation frame into a new window, or pop it back in if needed.
Interactively
This PR text

ENH: add option to pop out documentation frame

---

docs/source/release_notes.rst

Test suite is stable now until Travis ruins my day again
I'd like to tag and finally get a new conda env out

DOC: write release notes for v2.2.0, include missing notes from v2.1.0

---

docs/source/release_notes.rst

Small tag for the safety hotfix
It's tag day
This is docs
This is docs

DOC: add release notes for v2.2.1

---

docs/source/release_notes.rst

The last repo to put release notes on before the tags
I want to make tags

DOC: release notes for v2.3.0

---

docs/source/basic_usage.rst

* Some documentation additions
* I didn't see these touched on elsewhere, but if I missed them, then please disregard

DOC: CLI and sig:// usage

---

conda-recipe/meta.yaml

CI: pin back to 5.15 for CI issues

---

typhos/tests/test_widgets.py
typhos/widgets.py

Closes #502
Pulled out of #491 as it's still failing on CI
Test suite
Issue + PR

MNT/FIX: fontawesome deprecation of 'fa.'

---

typhos/tests/conftest.py
typhos/tests/plugins/test_core.py
typhos/tests/plugins/test_happi.py

Closes #503
Pulled out of #491 as it's failing on CI
Test suite
Issue, PR, test suite comments

TST: fix data plugin deprecations

---

docs/source/release_notes.rst

Write release notes based on the recent PR texts. Somehow it's all bugfixes and maintenance.
Let's tag
CI only
Is docs

DOC: write release notes for v2.3.3

---

docs/source/release_notes.rst

Bugfixes and maintenance
I want to tag every package that I help maintain since we haven't done this at all in 2023.
n/a
this is docs

DOC: write release notes for v2.4.1

---

README.md

Quick readme fix
There are probably more things to do

DOC: readme references to typhon, travis CI

---

conda-recipe/meta.yaml
docs/source/upcoming_release_notes/589-pydm_pin.rst
requirements.txt

Update PyDM pin to >=1.19.1 due to Display method being used.
Closes #589 
CI
Pre-release notes

BLD: update PyDM pin to >=1.19.1

---

.github/workflows/standard.yml
conda-recipe/meta.yaml
dev-requirements.txt

Update recipe, at the least the run requirements should be in sync with the conda feedstock
I get confused every time I see a conda feedstock pr
ci I choose you
This PR

BLD: update conda recipe
