pcdshub/typhos

- .coveragerc
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .landscape.yml
- .travis.yml
- requirements.txt
- run_tests.py
- tests/conftest.py
- tests/test_panel.py
- typhon/panel.py
- typhon/utils.py
Panel takes an arbitrary set of `EpicsSignals` and adds them to a single widget each labeled with an alias. The `Panel` handles making the correct control widgets based on whether the signal is read-nly, has separate read and write pvs e.t.c
For now, the `Panel` introspects the signal to get the name of the PVs. One could imagine in the future using `PyDMPlugin` to use the `EpicsSignal` directly.
This also adds, Travis, Codecov and Landscape configurations.
Closes #4 
Closes #6 
`Panel` has a specific test that instantiates all three types of signals. There is also `show_widgets` decorator that optionally shows the widget created by each test.
Sphinx docstrings for all classes and functions
> ENH: Create a Panel Widget

- .travis.yml
- dev-requirements.txt
- run_tests.py
- tests/conftest.py
- tests/test_display.py
- tests/test_panel.py
- typhon/display.py
- typhon/panel.py
- typhon/utils.py
- typhon/widgets.py
Certain PVs should not have a `PyDMLineEdit` given to them for control. Instead, we can use the the `PyDMComboBox` to show a limited amount of operations for the user. We do not need to identify what the specific states associated with the PV are, just that they are present. 
In order to still allow users to have ComboBoxes when creating a display for an offline device. Users can either set the `enum_attrs` attribute on their device, or explicitly add signals with the `enum` param on `Panel.add_signal`
Also:
* Now running flake8 in Travis. 
* Entire library now passes flake8 tests
* Cleaned the tests directory (qapp is instatiated automatically)
* PyDM is installed via conda recipe from `pydm-dev`
Closes #8 
Added two tests; one for the panel and one for the display
Clarified enum …
> ENH: Enum Handling

- tests/test_display.py
- tests/test_func.py
- tests/test_panel.py
- typhon/display.py
- typhon/func.py
- typhon/panel.py
- typhon/ui/base.ui
Add widgets to call functions in the user interface. This allows quick access to class functions that the user wants to expose. The function uses type hinting to creating the correct kind of widget for each chosen parameter, and also differentiates whether parameters are required or not. Similarly to the other panels, this can be hidden based on a button click. The parameter widgets are aware of their defaults and type to help the operator use the command correctly.
The PR also abstracts our Panel / hide_button setup to an arbitrary widget. This allows us to reuse the code in the `SignalPanel`, `FunctionPanel` as well as sub-panel for the optional kwargs. 
Closes #1 
Add tests for all added features
Document strings have been updated.
> ENH: Include functions in User Interface

- tests/test_display.py
- typhon/display.py
- typhon/func.py
- typhon/panel.py
- typhon/ui/base.ui
- typhon/utils.py
Include a `PyDMTimePlot` that plots devices `hints`. The device is queried for an attribute `hints` which is expected to be a dictionary which contains a list under the key `fields`. Each of these fields is then looked at in the `device.describe()` dictionary to find the actual PV name. This is then passed to `add_plotted_signal` to add to the `DeviceDisplay.hint_plot`
Closes #3 
Added a test to `tests/test_display`. All `EpicsMotor` sub-devices will also have plots.
Appropriate docstrings added
> Plot device hints

- tests/test_display.py
- tests/test_panel.py
- typhon/display.py
- typhon/func.py
- typhon/panel.py
- typhon/ui/base.ui
DeviceDisplay is now split into `TyphonDisplay` and `DeviceDisplay`. The base display instantiates all the widgets and panels but does not automatically enter anything. This preserves the feature set if someone wanted to make a `TyphonDisplay` without starting from an `ophyd.Device`. 
The `SignalPanel` how has an `add_pv` function. Most of the logic is included in this function. `add_signal` just rips the correct PV names from the given `EpicsSignal` and calls this function. This also means that PVs are stored as `(read_pv, write_pv)` instead of signals.
All tests use `using_fake_epics_pv`. This allows us to remove any need for checking if signals are connected inside the source code. 
* Deprecated `prefix_label` 
* Deprecated `enum_attrs`, we will assume that we can connect to PVs when …
> Refactoring

- tests/conftest.py
- tests/test_display.py
- tests/test_func.py
- tests/test_widgets.py
- typhon/display.py
- typhon/panel.py
- typhon/ui/base.ui
- typhon/ui/button.ui
- typhon/widgets.py
Instead of simple QPushButtons to switch between devices, we now have `ComponentButton`. These are placed in a vertical layout to the right of the main device display and function the same as prior QPushButtons did.
If you use `add_subdevice`, the `ComponentButton` will automatically be creating with the `hints` of the device. Otherwise the `ComponentButton` can have  PVs manually added via the function `add_pv`
Closes #19 
Added test for ComponentButton in `tests/test_widgets`
Updated docstrings
> Custom Device Buttons

- .travis.yml
- README.md
- conda-recipe/build.sh
- conda-recipe/meta.yaml
- dev-requirements.txt
When I tagged Typhon `v0.1.0` we did not have a dedicated Conda channel for the PCDS group so I didn't bother making a recipe. We now have `pcds-tag` and `pcds-dev` so this PR builds Typhon and deploys to the appropriate channel.
Also since creating the repository @ZLLentz laid out a way to do the Travis installation entirely via Conda. I think this is a more useful testing strategy as:
1) Most users will install via the Conda route
2) In prior iterations we would test and evaluate pull requests based on the `pip` install then only when the PR was merged would we see that the conda-recipe was invalid and the build would fail.
Finally, I added a build to the matrix that tests with `pydm-dev` instead of the tagged builds. This will allow us to use new features that haven't yet been tagged …
> CI: Installation via Conda

- tests/conftest.py
Updated my version of `pytest` and ran into this issue https://github.com/pytest-dev/pytest/issues/3413.
The TL;DR is a combination of the argument parsing in `pytest` and the default `argparse` library does not like when one command line argument is just a shortened version of another.  In `pytest=3.5` it appears they added arguments that start with `show` so when ever I tried to use my argument I received
```bash
$ py.test --show
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: ambiguous option: --show could match --showlocals, --show-capture
```
I have renamed `show` to `show-ui` and now there are no conflicts! Also, after #49 there is no need to have command line arguments to configure the logging setup. These have been deprecated.
> DEV: Modify pytest kwargs

- .travis.yml
- conda-recipe/meta.yaml
- dev-requirements.txt
- tests/conftest.py
- typhon/display.py
- typhon/signal.py
- typhon/widgets.py
Two minor changes to the grid setup.
1) Subclass `PyDMLineEdit` to set the `sizeHint`. Unfortunately this must be done on the class. 
2) Have the layout share the space between the `PyDMLineEdit` and `PyDMLabel` nicely.
> UI: Clean grid layout

- conda-recipe/meta.yaml
- tests/test_display.py
- typhon/widgets.py
* Fixes for issues caused by `ophyd=1.2` changes to `using_fake_epics_pv` and `hints` is now a `Device` property
* Do not reference the internal layout of `PyDMEnumComboBox` 
after https://github.com/slaclab/pydm/issues/315
> Fixes for Ophyd and PyDM lastest

- tests/test_display.py
- tests/test_widgets.py
- typhon/display.py
- typhon/ui/base.ui
In the new Typhon world order the `hint_plot` will be an expandable tool that will show up in the side bar of the application. This PR removes the `hint_plot` and all related functions and replaces it with  an image of the device. This is completely optional but it gives the user a better idea about what they are actually looking at. 
This is the last PR for now that will deal with the look of the main widget instead we will focus on the panel that allows operators to view other tools. This will restore the `hint_plot` functionality.
Closes #55
> API: Remove hint plot replace with PyDMDrawingImage

- .travis.yml
- MANIFEST.in
- conda-recipe/build.sh
- docs/source/basic_usage.rst
- setup.py
- tests/conftest.py
- tests/test_display.py
- tests/test_utils.py
- typhon/__init__.py
- typhon/ui/style.qss
- typhon/utils.py
Formalized loading of the custom Typhon stylesheet I've been assembling over the last few months. This by no means the last iteration, but I wanted to make sure we are placing this in a consistent place within the library and distributing it regardless of packaging choice.
* Use `conda-forge` version of `ophyd`
* Added a `style.qss` file in `typhon/ui`
* Added a helper function to load the stylesheet
* Update `MANFIEST.in` to store `ui` and `qss` files
* Test that we have all functionality when package is not installed from source. Tests are now done twice; once from source, once from install to check packaging instructions.
Closes #57 
We now run tests with the stylesheet by default. Also explicitly check the `load_stylesheet` function.
Added stylesheet instructions in Basic Usage …
> ENH: Typhon Stylesheet

- tests/test_display.py
- typhon/display.py
- typhon/ui/base.ui
- typhon/ui/style.qss
- typhon/widgets.py
Revamp the system where we display `Device` components. The goal was:
1) Make the system more extensible for "subdisplays" that were not `ophyd` Devices. These can now be placed in the `Tools` header.
2) Clean the UI to make it look more professional.
This breaks some of the existing API to make functions and widgets have future-proof names
* `component_widget` is now called `subdisplay`
* `device_button_group` has been deprecated
* `add_subdisplay` no longer accepts a custom button type
* `hide_subdevices` is now called `hide_subdisplays` 
Closes #27
Closes #56 
Added a full test of the sidebar logic in `test_subdisplay`
Updated docstrings
> API: Sidebar

- docs/source/connections.rst
- docs/source/index.rst
- docs/source/plugins.rst
- tests/test_plugins.py
- typhon/plugins/__init__.py
- typhon/plugins/core.py
This should look very familiar. The last attempt did not take into account that we never want to recreate `ophyd` signals in the new `PyDMConnection` object. This new approach abandons the idea that we would every want to support the `SignalPlugin` from the `QtDesigner`, instead you register all the signals that you will need to create links for; then create the widgets that reference those signals.
```python
syn = ophyd.SynSignal(..., name='test_signal')
register_signal(syn)
widget  = PyDMWidget('sig://test_signal')
```
This is a little cumbersome but in reality most users will not be calling these by themselves. When they create a `DeviceDisplay` we can pass through their device and register signals for them.  
**Note** This won't pass all the tests until a new tag of PyDM is created …
> ENH: SignalPlugin

- tests/test_display.py
- tests/test_signal.py
- typhon/__init__.py
- typhon/signal.py
- typhon/utils.py
`SignalPanel` made the assumption that we would only display `EpicsSignal` objects. After #63 we can now display an `ophyd` Signal. There is also one major API change where we kept the underlying signal mapping of signals to rows that was called `pvs`. This no longer makes sense now that this can contain arbitrary signals. 
Closes #43 
More rigorous testing included in `test_signal` functions.
> ENH: Signal Abstraction

- .travis.yml
- tests/test_display.py
Test with fully simulated `ophyd` Device. Added some signals that update randomly in the background. Makes it surprisingly fun to plot stuff. We have also rid ourselves of the `using_fake_epics_pv` race conditions! Also no longer need the Docker container. Not sure we ever really needed it to be honest.
Closes #67
> TST: MockDevice has no EPICS

- .travis.yml
- conda-recipe/meta.yaml
Newest versions of `ophyd` and `PyDM` are required. By serendipity the version numbers for both are identical.
> BLD: Update Dependencies

- typhon/plugins/core.py
- typhon/utils.py
* We should be able to get the `"precision"`from the description of the signal. This is then communicated to the widget through the `precision_signal`.
* Before https://github.com/slaclab/pydm/issues/282 is resolved we need to set the alarm state to avoid a `"Disconnected"` border.
* One minor improvement to the `clean_attr` functions to deal with attributes that have `.` in them still
> FIX: Extra SignalPlugin features

- typhon/plot.py
- typhon/ui/plot.ui
Before we only displayed the signals associated with the highest level device as available in `DeviceTimePlot`. This PR now adds the child signals so they can be plotted as well.
Closes #79
> FIX: Show child signals in plot

- .travis.yml
- README.md
- conda-recipe/meta.yaml
- requirements.txt
- tests/conftest.py
- tests/test_utils.py
- typhon/ui/style.qss
- typhon/utils.py
`QDarkStyleSheet` is now packaged with the repository. It was used in the tests before but never anywhere in the actual library. Since this is now built on the `pcds-tag` channel I feel comfortable making it an actual dependency. To use the stylesheet I added a `dark` optional keyword on `typhon.use_stylesheet`. This allows a convenient way to load the stylesheet into your application. 
* I also fixed an error in the light stylesheet that raised a warning about `bold` not being an .  
available option on `QListWidget::item`. 
* Since our standard PCDS environment uses the `conda-forge` builds of `ophyd` and `bluesky` I removed the `lightsource2-tag` channel from all tests.
> ENH: Official support for QDarkStyle

- tests/test_signal.py
- typhon/display.py
- typhon/signal.py
Noticed today that we require `title` as an argument of `SignalPanel` but we then just drop it on the ground. I will remove this in a future release but I have pledged a level of stability so I'll mark it as deprecated for this release, then remove it the one following.
For now, we warn and any internal usage of "title" in `typhon` has been removed.
> DEP: Remove unused Title Argument

- .travis.yml
- typhon/plugins/core.py
Ran into an `ophyd.Signal` that raised an exception upon subscription.  The `SignalPlugin` did not wrap `subscribe` up in a `try / except` block which brought everything to a screeching halt.
Now, the solution is not quite so simple as just adding the `try` block in `SignalConnection`. If we raise an error on subscription we **want** that `SignalConnection` to explode. Otherwise we run the risk of subscribing a bunch of channels to a connection that will never update! So instead my solution was to add this to the `add_connection` block. If we fail to subscribe we make sure not to save the `SignalConnection` and the next channel that needs the `signal` will try again.
@hhslepicka Does this belong in PyDM? Or are `PyDMPlugin` objects responsible for catching their own kind of exceptions?
> MAINT: Catch exceptions created on Subscription

- docs/source/connections.rst
- tests/conftest.py
- tests/test_plugins.py
- tests/test_signal.py
- typhon/plugins/core.py
- typhon/signal.py
- typhon/widgets.py
Some general improvements to the `SignalPlugin`
* We now inspect the `describe` dictionary of the `Signal` for `"enum_strs"`, `"units"` and `"precision"`. I also left this pretty extensible so that in the future as long as we have a describe key that maps to a signal it is just a matter of adding a tuple. 
* Very much the successor to #91, there was the potential for exceptions on `get` when setting up our signal that would not have been caught. We now wrap these up nicely. Also now that `SignalPlugin` handles some of the error handling I moved more things there. It makes more sense to not create a `SignalConnection` at all if you give me the name of a non-existant `Signal`.
There is still the potential for a few strange edge cases to arise if our network is unstable. For instance if we …
> ENH: Signal Metadata

- docs/source/widgets.rst
- tests/conftest.py
- tests/test_plugins.py
- tests/test_signal.py
- typhon/signal.py
In other places outside of the `SignalPanel` it is useful to have the function to get a widget based on a `ophyd.Signal`. I pull this out of a class method and made it a general function.
> MAINT: Pull signal widget logic out of SignalPanel

- conda-recipe/meta.yaml
- dev-requirements.txt
- requirements.txt
- tests/test_display.py
- tests/test_plot.py
- tests/test_plugins.py
- typhon/display.py
- typhon/func.py
- typhon/plot.py
- typhon/plugins/core.py
- typhon/signal.py
- typhon/utils.py
- typhon/widgets.py
Future releases of `PyDM` will no longer contain the homebrewed `PyQt` interface layer. This eliminates any dependency on those imports and instead used the agreed upon `qtpy` layer.
I also noticed that `numpy` is imported but is not explicitly listed as a dependency. If there is ever a world in which all of the `typhon` depndencies do not also depend on `numpy` we are now prepared.
Finally, in `ophyd=1.3` three new signals were added to `ophyd.sim.SynAxis`. These are effectively plotted by the `DeviceTimePlot` but the test had the number fixed to '2'
Closes #94 
Existing tests
> MAINT: QtPy Interface

- tests/test_display.py
- typhon/display.py
Complicated devices like `AreaDetector` may have a large number of child components. For applications like the `lightpath` we may not need to create displays for all these as connections take time. This PR makes the choice to draw widgets for `children` an option in `__init__`.
Added a test for new feature
Added option  to docstring
> ENH: Childless DeviceDisplay

- tests/test_utils.py
- typhon/display.py
- typhon/plugins/core.py
- typhon/signal.py
- typhon/utils.py
Sometimes you have to use stuff twice to figure out what is useful and what isn't. These utilities are now all being used in the `lightpath` and there were assumptions made in various places that I'd like to unravel. 
* Reduced the `log` level of registering a signal twice. This isn't really a huge deal and checking prior to every signal add is cumbersome.
* We no longer "guess" by capitalizing names in `clean_attr`. It works sometimes but fails for any form of three letter acronym e.t.c
* Add a `is_signal_ro` utility. Someday we may be able to introspect an `ophyd.Signal` but for now we have to check the class. This future proofs us to just change the utility function instead of searching through code
* `grab_hints` is a convenient function to find the hints of a Device. This is a little …
> MAINT: Utility Extensions and Modifications

- typhon/plugins/core.py
Thought I was having an issue with `PyDMEnumComboBox` for days but just realized that the `SignalPlugin` sends the new value before ever sending the `metadata`. We then try to set the value of the `QComboBox` before we have filled it with any information.
This is a good thing to keep in mind for general `Plugin` logic. We can't assume that we are sending this information to `state-less` widget and it would be nice to ensure that all the widgets depend on the same order of information.
> FIX: Send signal metadata before value

- .gitignore
- .travis.yml
- docs/Makefile
- docs/source/basic_usage.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/tools.rst
- docs/source/widgets.rst
- tests/test_log.py
- tests/test_plot.py
- typhon/display.py
- typhon/signal.py
- typhon/tools/__init__.py
- typhon/tools/core.py
- typhon/tools/log.py
- typhon/tools/plot.py
Created a base API for all `typhon` tools to follow. This makes official the new structure in which every tool can be instantiated by itself, but if you want to automatically make it useful with an object you can use a `from_device` class method instead.
Also made a new widget `TyphonLogDisplay` to contain the `PyDMLogDisplay` widget. This was necessary to support multiple devices logging to the same widget. It also leaves room to expand the feature set of the widget to save the log, post to elog e.t.c
Closes #106 
Part way to addressing #107 
Added test for `TyphonLogDisplay`
Documentation has been ignored for too long. Addressing this in the following PR
> MAINT: Tool Restructure

- .travis.yml
- conda-recipe/meta.yaml
- dev-requirements.txt
- docs/source/tools.rst
- requirements.txt
- tests/test_console.py
- tests/test_display.py
- tests/test_suite.py
- typhon/suite.py
- typhon/tools/__init__.py
- typhon/tools/console.py
- typhon/utils.py
Added `QtConsole` as `TyphonConsole` tool. This allows operators to access Python functions that may not be accessible through the GUI. The most difficult part was passing through a `Device` to the completely separate process. I got around this by dumping the Device into `json` using `happi` and the picking it up on the other side. 
**Note**: I tried to do this with `tempfile` and couldn't get it work which is why I make a random filename myself
Closes #74 
Tests creation and `happi` device loading
Added to `tools` autosummary
> ENH: QtConsole

- conda-recipe/meta.yaml
- requirements.txt
- tests/plugins/happi.json
- tests/plugins/test_core.py
- tests/plugins/test_happi.py
- typhon/plugins/happi.py
A `PyDMPlugin` that can transmit objects and their metadata. This uses the proposed model that will be used in `PyDM` for structured data in the future. There is one signal that sends a dictionary of information to subscribers and it is up to them to parse it. In this case it includes the instantiated object (usually an `ophyd.Device`) and the `happi.Device` that it came from.
Thoughts
-------
This does the job of getting devices to widgets but is kind of awkward in some ways. For instance, if another widget requests the same device, we don't want to send out that information again (might be more expensive to redraw entire devices). In fact we really only want to send the device once, I hope I'm not slamming a round peg in a square hole here
Closes #38 
Added tests for adding …
> Happi Plugin

- README.md
- bin/typhon_designer_plugin.py
- bin/typhon_env.sh
- conda-recipe/build.sh
- tests/test_utils.py
If installed via CONDA, `typhon` widgets will now automatically be available in Designer. For development, the `typhon_env.sh` script can be used to set everything up as well. The PYDM_DESIGNER_ONLINE variable is set up as well, otherwise the Typhon widgets will not update as you change parameters.
Closes #129 
Test will be run if we believe the package to be installed via CONDA
> Designer Environment

- tests/test_display.py
- typhon/display.py
- typhon/suite.py
Played around with the API of `TyphonDisplay` today, trying to put it in a `TyphonSuite`, and it really was awkward. I think this solution is a lot more intuitive. What you really want to do is not just specify a static template but specify a template for each kind of display (if you aren't already using `happi`). That way you still get the full feature set of swapping around the `TemplateType` but you can modify the behavior at whichever stage you deem necessary. For instance, the situation where you wanted a custom embedded template but wanted to use the other defaults was hard to specify in the old API.
`use_template`is gone, instead there are just properties for each type `embedded_template`, `display_template` e.t.c. The template priority that is used is as follows:
1. If …
> TyphonDisplay API

- tests/test_suite.py
- typhon/suite.py
The goal is to be more flexible with how we add widgets to the sidebar. Before we had one category for "Devices" one for "Tools" and and that was it. In reality, if you get more than a few devices in the suite you may want to start breaking this up into more fine grain categories (below motion and diagnostics are separated). 
In order to accommodate this I had to change how we searched through the `ParameterTree` to find relevant object and keep the docking status inline with the tree button.
I also had deprecated the `add_subdevice` method. But in line with other PRs I don't want to keep that kind of flotsam around this early in the project so it is officially gone.
Closes #133 
Revamped test suite for TyphonSuite 😄  Unit tests are more unit-like
Updated docstrings as well
> Device Categories

- run_tests.py
- tests/test_suite.py
- typhon/suite.py
You now have the option to `embed` an screen in the `TyphonSuite`. Instead of launching a new `QDockWidget` we tile these windows together in a single layout to use space efficiently. This allows operators to toggle the views of their system and the depth they want to see device information.
In code this meant:
* Factoring code out of `show_subdisplay`  into `_show_sidebar`. This function largely does the legwork of making sure that our widget docking system stays in sync with the available actions in the parameter tree
* Creating a `embed_subdisplay` method to setup the layout and `embedded_dock` correctly
* Modify `hide_subdisplay` to handle embedded windows slightly differently.
Also on the side:
* I set the logging setup to only capture `typhon` messages.`PyQt` creating a logging …
> Embedded Windows in Suite

- conda-recipe/meta.yaml
- setup.py
- `setuptools` is required for package setup
- The message produced in `setup.py` was not correct, this should be remedied now.
> Fix Setup and Recipe

- tests/test_display.py
- tests/test_utils.py
- typhon/display.py
- typhon/signal.py
- typhon/utils.py
Add a few utility properties and names for use with stylesheets:
Added read-only `pyqtproperty`s `device_name` and `device_class`. This allows you to set a template from a stylesheet like:
```css
TyphonDisplay [device_class='ophyd.sim.SynAxis'] {qproperty-force-template: '/path/to/my/template.ui'}
TyphonDisplay [device_name='test_motor']{...}
TyphonDisplay [device_name='test_motor'][display_type='1']{...}
```
* You have to use the integer spec for the `display_type` enum. This could be remedied by adding another property that is the string but I hate the redundancy and an obvious name for the new property escaped me
* The `device_class` is just string matching. No inheritance is respected. Probably not a huge deal but if we start having classes like `AreaDetectorV26` it might get …
> Panel and TyphonDisplay Stylesheets

- tests/test_func.py
- tests/test_status.py
- tests/test_utils.py
- typhon/designer.py
- typhon/func.py
- typhon/signal.py
- typhon/status.py
- typhon/utils.py
- typhon/widgets.py
A button you can drag into `QtDesigner` to run a function. The button accepts an object (either added programmatically or via a `happi` plugin), a `method_name` and whether or not we `use_status` to give the button some state. By default, if `use_status` is `True` we disable the button while the underlying operation is in progress.
In order to show any error messages that may pop up during the execution of the function I made the general `raise_to_operator` method that displays an `Exception` and corresponding `traceback` in an `QMessageBox`
Closes #103 
Closes #126 
Lots of tests. Coverage is going to be low on the `TyphonStatusThread` because it is run mostly inside a `QThread` however all the endpoints are checked in the test suite so it is surely being executed.
> Method Button

- requirements.txt
- tests/plugins/test_happi.py
- typhon/plugins/__init__.py
Make `happi` an optional dependency. The only place it was imported before without a `try/except` is in the `HappiPlugin`. This is now protected. In the future we can make a compatibility layer with whatever other device server we happen upon. But until we find a second alternative to `happi` I'm going to hold off.
@tacaswell 
Added a test, largely to protect against regression
> No happi no cry

- tests/test_status.py
- typhon/plugins/core.py
- typhon/plugins/happi.py
The test suite is a little unstable and I think may have finally figured out why. In `PyDM v1.6.0` there is now a `destroying` keyword on disconnect which basically lets us know that the `QWidget` which holds the `PyDMChannel` is being garbage collected, not just disconnected. So instead of making sure everything is disconnected on an object that is "between worlds", we just let it pass by. The fundamental reason for this a lot of 💩happens when an `QObject` still has a `Python` representation but doesn't exist in the `C++` layer or vice versa. The `destroying` key was not implemented in either of the `Typhon` plugins which I think is why we were seeing segfaults on fixtures that were continually torn down and re-initialized. 
Secondly, with the `status` tests I was seeing some hangs when …
> Plugin and Test Suite Cleanup

- conda-recipe/meta.yaml
- docs/source/cli.rst
- docs/source/index.rst
- requirements.txt
- setup.py
- tests/happi.cfg
- tests/test_cli.py
- tests/test_display.py
- tests/test_suite.py
- typhon/cli.py
- typhon/display.py
- typhon/plugins/core.py
Typhon command line utility to create a `TyphonSuite` with a group of devices. User passes in a list of devices by name and optionally:
* `--version` just to print information about where the utility comes from
* `--debug` to blast all information from the root logger. Otherwise the `INFO` stream is used from the `typhon` logger
* `--dark` to use `QDarkStyleSheet`
* `--stylesheet` if you want to pass in a custom stylesheet. In my mind this will be for specifying device specific screens e.t.c, not just base widget styling, but the option is there as well.
* `--happi-cfg` if you want to point at a specify `happi` configuration file. Otherwise environment variables are used.
Also saw a few more issues when testing on my fork with freezes on Travis. Explicitly disconnecting a few of my …
> Typhon Command Line Utility

- .travis.yml
- tests/test_display.py
- tests/test_signal.py
- tests/test_suite.py
- tests/test_utils.py
- tests/test_widgets.py
- typhon/cli.py
- typhon/plugins/core.py
- typhon/plugins/happi.py
- typhon/suite.py
Thank you @hhslepicka @klauer! I think everything should be far more stable. Issues resolved in this PR:
1. Creating another `QApplication` is bad. I thought this exploded on sight but it doesn't, in fact sometimes the test suite passed. No idea, but removing this mistake seemed to stop the major problems seen locally.
2. In `TyphonSuite` I was creating widgets then not setting their parents. This never caused a problem in actual use, but when I thought `qtbot.addWidget` would clean these up, they would not get found because they were children of the `QApplication` itself. I think this caused some of the sporadic freezes seen before. I now explicitly call `setParent` on these so they will be captured by anything that affects the children of `TyphonSuite`
3. There were a few tests I was …
> Fixes to Testing Suite

- docs/source/index.rst
- docs/source/positioner.rst
- run_tests.py
- tests/conftest.py
- tests/test_positioner.py
- typhon/__init__.py
- typhon/designer.py
- typhon/display.py
- typhon/func.py
- typhon/positioner.py
- typhon/ui/detailed_positioner.ui
- typhon/ui/embedded_positioner.ui
- typhon/ui/positioner.ui
- typhon/ui/style.qss
- typhon/utils.py
Added `TyphonSetWidget` for widgets that have `set` methods which take numbers. It also has widgets for limit switches, soft limits if those signals exist, otherwise they are hidden. I also created full templates that use this widget so they can be utilized easily via stylesheet.
Closes #37 
Full test file added
> Positioner

- README.md
- docs/source/basic_usage.rst
- docs/source/display.rst
- docs/source/python_methods.rst
- docs/source/tools.rst
- tests/test_cli.py
- tests/test_designer.py
- tests/test_display.py
- tests/test_plot.py
- tests/test_signal.py
- tests/test_suite.py
- tests/test_utils.py
- typhon/__init__.py
- typhon/cli.py
- typhon/designer.py
- typhon/display.py
- typhon/signal.py
- typhon/suite.py
- typhon/tools/plot.py
- typhon/ui/detailed_positioner.ui
- typhon/ui/detailed_screen.ui
- typhon/ui/embedded_screen.ui
- typhon/ui/engineering_screen.ui
- typhon/utils.py
Last round of API breaks I wanted to get in before I tag:
I really didn't like how vague the names were for `TyphonPanel` and `TyphonDisplay`. They convey very little meaning. They are now `TyphonDeviceDisplay` and `TyphonSignalPanel`. A little wordier but easier to tell what they are going to do
After a conversation with @klauer, lugging a bunch of API from `v0.1.0` around probably isn't necessary. Now that every `typhon` widget has `.from_device` class constructor I don't need factory functions so that removes any need for `DeviceDisplay` and `DeviceTimePlot`. There was also an old utility called `grab_hints` which has been replaced by the more general `grab_kind`
Also a few small fixes:
*  The `typhon` command line function was not loading any of the tools
*  The `typhon` widgets in …
> API Breaks and Deprecations

- .travis.yml
- docs/source/basic_usage.rst
- docs/source/index.rst
- docs/source/save.rst
- docs/source/utils.rst
- tests/test_cli.py
- tests/test_suite.py
- tests/test_utils.py
- typhon/__init__.py
- typhon/cli.py
- typhon/suite.py
- typhon/utils.py
Woo hoo! Closing the 4th oldest issue in the library.
The idea here is if I add a bunch of devices to my `TyphonSuite` then decide I will want to reload this later, how can I save and reload this object. After a conversation with @klauer and @hhslepicka I decided to see how the route of actually saving the Python code required to generate the ``TyphonSuite`` looked. A button was added to the ParameterTree so that this is available via the GUI.
I did something which I think is clever here and broke up the `typhon.cli` library in order make a terse template that either can be executed as a standalone Python script or imported and used as part of a bigger Qt application. By using the `typhon.cli` you will still have access to all the additional options:
```
$ python my_saved_suite.py …
```
> Suite saving

- examples/panel.py
- tests/plugins/test_core.py
- tests/test_signal.py
- tests/test_widgets.py
- typhon/plugins/core.py
- typhon/signal.py
- typhon/widgets.py
Previously `typhon` just threw array data on the floor when it found it in a `Signal`. With this PR we now create a `QPushButton` that either launches a `PyDMWaveformPlot` for a one-dimensional array or a `PyDMImageView` for two-dimensional. Unfortunately, PyDM doesn't deal with colored images so still can't handle that.
I think this is better for the long term instead of just showing them directly inside the grid. It doesn't scale well for multiple arrays, but I'm open to alternative opinions. My thought is you can always customize your template to include a full size widget.
I also think that using my test suite to visually check all the widgets might have reached a tipping point. I put a small examples folder in with a fake device and panel to mess around with.
Closes #97 
Tests for …
> Array Data

- tests/plugins/test_core.py
- typhon/display.py
- typhon/func.py
Found a few of these when setting up the demo and also included a patch that is required after https://github.com/slaclab/pydm/pull/470
1. If we fail to call a function it will not produce a `Status`. We now have a check to see that we are ready for this scenario.
2. Not all widgets inherit from `TyphonBase`, the `TyphonMethodButton` for instance. We still want to auto populate as much as we can, i.e if a user drags in a `TyphonMethodButton` into their template we should fill it.
3. The `_unit` variable no longer exists on `PyDMWidgetBase` but instead only on widgets that inherit from `TextFormatter`. Simply using ` PyDMLineEdit` in the test will work and be back compatible.
> Small bugs

- tests/test_signal.py
- typhon/signal.py
We were creating the same widget twice for an writeable array. Someday we'll have a widget that can write back to an array but I don't quite see a use case at the moment. For now, there is no point of having two identical buttons next to each other in the panel. Regression test added. 
Closes #177
> FIX: Double SignalDialogButton

- tests/plugins/test_happi.py
- typhon/plugins/happi.py
If we have a device in `happi` which has a component device that we want a screen for say `reference_laser.y`, we want to be able to grab these devices easily. This PR supports dotted access to components as specified in the channel:
`happi://reference_laser.y`
Closes #182 
Tests added
> Child Access through HappiPlugin

- typhon/positioner.py
- typhon/signal.py
- typhon/utils.py
Suggested as a follow-up to #174 by @teddyrendahl 
Use Component docstrings when creating Typhon widgets
Closes #167 
Example screenshot:
> ENH: component.doc

- conda-recipe/meta.yaml
- requirements.txt
- tests/test_func.py
- typhon/func.py
Closes #171
If numpydoc is decided to be too heavy of a dependency, this could be made optional.
Example
---------
> ENH: add tooltips to function buttons + parameters

- tests/conftest.py
- tests/test_cli.py
- tests/test_log.py
- tests/test_utils.py
- typhon/cli.py
- typhon/tools/log.py
- typhon/utils.py
Noticed then when actually trying out the `typhon.cli` in the wild. If you mistype your device name i.e: `typhon not_a_device`. The CLI goes through all the trouble of creating a `TyphonSuite` for you that contains **no** devices. Not optimal.
This PR rearranges the code in the CLI function so we exit as early as possible if you entered malformed device information. The code is a little messier but I think this is better for the end user. The other commits were centered around the fact that I created and loaded a device-less `TyphonSuite` to test the command line interface so those tests had to be updated.
Closes #184
> CLI Cleanup

- requirements.txt
- tests/plugins/test_happi.py
- typhon/plugins/__init__.py
- typhon/plugins/happi.py
- typhon/widgets.py
Not sure how my the test included in #150 didn't catch this, I'll take a closer look at a later date. This will fix the issue where `HappiChannel` was not being imported when `happi` is not present. In actuality `HappiChannel` has no `happi` dependency so it can be moved to an accessible location inside the main library.
Closes #198
> MAINT: Move HappiChannel

- conda-recipe/build.sh
`PYQTDESIGNERPATH` is not set when the CONDA package is built. With macro expansion this leaves the activation file as:
`export $PYQTDESIGNERPATH=/path/to/my/module/designer.py:`
This obviously does not work when multiple libraries plan on loading designer plugins. This has the side affect of not clearing the variable when you activate a new CONDA environment. However, as long as these libraries are setup to `unset` on deactivation you should have no problem switching.
> FIX: PYQTDESIGNERPATH variable should not be expanded

- typhon/signal.py
When the signal is noted to be a string (e.g. `Cpt(EpicsSignal, ':TEXT', string=True`), make sure it is displayed as a string in the ui.
Char arrays default to showing the integer values, but these are often used to hold string data and expect the client to translate.
Worked for me, but clearly needs some more rigor.
N/A
> FIX: certain char array PVs should show as strings

- typhon/display.py
Add the `device.prefix` to the macros even if the device is not loaded from `happi`. Conditional is present to account for `ophyd.sim` objects
Closes #207
> Prefix Metadata

- .travis.yml
- README.md
- dev-requirements.txt
- requirements.txt
- tests/test_utils.py
External collaborators seem to prefer `pip` installing instead of using our CONDA channel. Since both `timechart` and `pydm` are both now on PyPI I decided it was time to add this as a branch in our testing suite and officially support this installation pattern.
Also since Python 3.7 is passing now, I'm removing it from the `allowed_failures` list 🎉
> Use PyPI on Travis

- .travis.yml
- tests/test_display.py
- tests/test_signal.py
- tests/utils/display.py
- typhon/display.py
This allows a user to specify a Python file instead of a `.ui` as a Typhon template. The Python file must contain a subclass of the `pydm.Display` in accordance with the mandates required by PyDM
@hhslepicka Is this the correct future-proof way of doing this? Seemed pretty easy. Don't know why I was whining so much in the linked issue
I also found a bug where calling `TyphonDeviceDisplay.load_template` without any macros overwrote the cached macros from prior loads which kind of made caching the macros pointless. This is now remedied. 
Closes #201
> ENH: Python file as a template

- tests/conftest.py
This fixed some problems I found locally with the test suite. The issue is that the QtConsole wants to spawn a Jupyter kernel behind it. Standing a bunch of these up and down in rapid succession seems cause ... issues. This may be a worrying sign or maybe just something that happens in test suites and not elsewhere.
> DEV: Patch TyphonConsole in test suite

- README.md
That way leads to segfaults.
Creating two QApplications in one Process leads to segfaults
The copy-paste example should not run the risk of segfaulting an
in-use IPython session that already has a QAppliaction from mpl
N/A
It _is_ documentation.
> DOC: make sure we don't create two QApplications

- typhos/suite.py
- typhos/utils.py
- I made the stupid mistake of trusting QMovie to close the file, which it clearly doesn't do. Now we cache the loading GIF in the class. This fix the `Too many open files`... sorry @ZLLentz for wasting your time...
- There is no point of showing up all the subdevices in a device tree (e.g. Area Detector with its dozen of subdevices). So we limit it to 1 subdevice level.
> FIX: Too Many Files and Subdevices depth

- typhos/widgets.py
This PR tries to be a bit smart on using an adequate displayFormat depending on the kind of information we are displaying. This was caught by @slacAdpai while testing an expert screen generated via `Typhos` in which the displayed value did not match the display at the `pcdswidgets` readback. That was due to the `displayFormat` that was set to be `Exponential` in one and `Default` at the other. With this PR we try to be a bit smart at the autogeneration and rely at the EGU information coming from the control system to switch.
Engineers and scientists would like to properly see the value of the readings.
Locally
> ENH: Use exponential displayFormat if EGU requires it.

- typhos/ui/style.qss
The Typhos stylesheet was not restricting the selection to descendants of TyphosBase but instead it was affecting other widgets with its rules.
This PR restricts the selection to descendants of TyphosBase.
Other screens being launched from an application that applied the Typhos stylesheet were looking wrong and having a completely wrong appearence.
Locally
> FIX: Make sure that the stylesheet is not affecting the widgets that are not Typhos

- conda-recipe/meta.yaml
- requirements.txt
- tests/test_cli.py
- typhos/cli.py
- typhos/display.py
ENH: Add option at typhos.cli to allow for users to pass a class and args.
ENH: Added TyphosDeviceDisplay.from_class to allow a display to be created via a class and args/kwargs.
BLD: Added dependency for pcdsutils.
TST: Added tests for the new cli functionality.
@klauer mentioned that it would be really useful for engineers and users in general to be able to quickly check a screen for a particular device.
Now the `typhos` command line interface allow that by passing a class and kwargs in the following format:
```bash
$ typhos "package.ClassName[{"arg1":"val1",...}]"
```
The command line interface still support Happi entries and they can be mixed together.
New tests added for `typhos.cli`.
argparse help was expanded to also describe the possibility to load from a class.
This PR depends on …
> ENH: New typhos cli functionality

- examples/panel.py
- tests/test_positioner.py
- typhos/utils.py
Seems the right way since we now assume ophyd 1.4
Upstream patch to fix write_access issue: https://github.com/bluesky/ophyd/pull/813
> REF: define SignalRO in only one place

- tests/test_utils.py
- typhos/display.py
- typhos/utils.py
Working toward closing #248 
cc @ZLLentz
> ENH: rework how device templates are found

- typhos/display.py
Provide users a way to change the current `template` in use via a Context Menu.
As we move ahead with the development of Templates and even the ability to specify templates based on the class hierarchy of devices it is desirable to have the option to pick which template best fits the need for a certain task.
Locally
N/A
> ENH: Add context menu to switch template.

- tests/plugins/test_core.py
- tests/test_display.py
- tests/test_signal.py
- typhos/designer.py
- typhos/display.py
- typhos/suite.py
- typhos/ui/detailed_positioner.ui
- typhos/ui/detailed_screen.ui
- typhos/ui/embedded_positioner.ui
- typhos/ui/embedded_screen.ui
- typhos/ui/engineering_screen.ui
- typhos/utils.py
Having quick access to switching displays I think will be a useful thing:
Left-click for a quick swap to the "best" embedded/engineering/detailed display.
Right-click to choose a specific embedded/engineering/detailed display.
Alternatively, the display context menu was tweaked a bit:
I think we can do better widget/style/etc. wise, so consider this a proof-of-concept.
This PR also entirely reworks how displays are searched for and loaded.
TODO
> ENH: entirely rework display loading mechanism, add display switcher

- tests/test_widgets.py
- typhos/widgets.py
Closes #226
Originally this started as a drop-down for setpoint line edits, but I think it might fit more neatly in the context menu as pydm already modifies it:
Functionality:
* Records entries as the user adds them to the item, along with a timestamp.
* Displays history in context menu
* Limits history to a designable Property value (0 to disable entirely)
* Tweaks the menu font to allow for visual alignment of timestamp/value
> ENH: add setpoint history context menu entry

- tests/test_plot.py
- typhos/tools/plot.py
- typhos/utils.py
Closes #194
* Adds a suite of utilities for dealing with ophyd subscriptions in a temporary sort of way (with context managers)
* Adds a QThread wrapper that emits events for connections
* Hacks on some signal-handling to see if a `Signal` might not emit a connection callback (because ophyd is busted)
* Limits number of channels automatically added as hints
* Uses fully-qualified names (root.name + `dotted_name`) for signals added to the plot
What else, @hhslepicka, do we need here?
> REF/FIX: plot rework + background connections

- tests/test_display.py
- tests/test_signal.py
- tests/test_suite.py
- typhos/cli.py
- typhos/display.py
- typhos/signal.py
- typhos/suite.py
- typhos/ui/detailed_screen.ui
- typhos/ui/detailed_tree.ui
- typhos/ui/embedded_screen.ui
- typhos/ui/engineering_screen.ui
- typhos/ui/style.qss
- typhos/utils.py
- typhos/widgets.py
Add a new signal panel which aids in the display of complex devices
ophyd Devices comprised of signals + sub-devices are problematic in typhos.
This PR adds a new signal panel which can show a complex device in a view that retains the structure laid out in the original ophyd definition.
Take, for example, a simple 3-motor device:
```python
class MyThreeMotorDevice(ophyd.Device):
m1 = ophyd.Component(ophyd.EpicsMotor, 'm1')
m2 = ophyd.Component(ophyd.EpicsMotor, 'm2')
m3 = ophyd.Component(ophyd.EpicsMotor, 'm3')
config = ophyd.Component(ophyd.EpicsSignal, "config_pv")
```
Typhos master would aggregate all signals from this device and group them according to `Kind`. To change that behavior would require adding a new template called `MyThreeMotorDevice.template_type.ui`.
With this PR, the …
> ENH: Composite signal panel + configuration drop-down + filtering

- typhos/utils.py
- typhos/widgets.py
Add a class attribute `persistent` to `SignalDialogButton` allowing us to configure wether or not the dialog generated to display the widget will be available even if the parent is destroyed or not.
This change allow us to have images and plots as standalone dialogs even if we change the layout or if we close the current screen for a device.
That is useful when performing diverse operations.
Locally.
N/A
> ENH: Allow SignalDialogButton to produce persistent widgets.

- typhos/cli.py
A quick attempt at closing #271, allowing me to run `typhos` with full `class[{kwargs}]` syntax without having to jump through hoops and specify a temporary HAPPI_CFG.
Not sure if @ZLLentz saw more here than I did. Perhaps it could be handled better?
> FIX: do not require happi on the command line

- typhos/cache.py
Maybe not the best solution but a solution so far...
Closes #288 
While debugging this issue I noticed that if a value never arrived and describe is called at a signal it may report the wrong information which is what happened with the Image Button.
This fix calls get to force a prime of the value at the signal. I am not sure yet if there is a better way to address this issue. I will look into it for a bit to try and identify if the value callback was executed at least once so we can avoid this "HACK".
Fix the issue #288.
Locally tested with IOC.
N/A
Before the fix:
After proposed fix:
> FIX: Prime signal value before describe.

- typhos/cache.py
- typhos/display.py
- typhos/utils.py
master baseline on NFS: 
```
In [1]: %timeit list(typhos.utils.find_templates_for_class(ophyd.EpicsMotor, 'embedded', paths=typhos.utils.DISPLAY_PATHS))
2.93 ms ± 12.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
This PR:
```
In [2]: %timeit list(typhos.utils.find_templates_for_class(ophyd.EpicsMotor, 'embedded', paths=typhos.utils.DISPLAY_PATHS))
1.08 ms ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
This is called 3x per display, and each call time scales linearly with `len(cls.mro())`
So assuming 200 devices, baseline should be 200 * 3 * 3ms = 1.8sec
With this, 200 * 3 * 1ms = 0.6s
Moving the caching up a level as in 18dbeb5, should reduce this by ~3
Not sure it's worth the complexity just yet
Alternatives
-------------
* LRU cache (builtin) - and …
> Path caching in `find_templates_for_class`

- typhos/display.py
- typhos/panel.py
- typhos/utils.py
> FIX: do not fail if `unsubscribe` fails; mark nested devices

- typhos/tools/plot.py
Less a fix, more a "catch after the fact and silence"-sorta thing.
Closes #300
> FIX: plot teardown race condition causing CI failure

- typhos/cli.py
- typhos/display.py
- typhos/panel.py
- typhos/suite.py
- typhos/ui/style.qss
* Changes row labels and titles to be in terms of pixel units. See screenshots below and related issue for details.
* Uses stylesheet instead of code for titles
* Add title for Typhos suite to get rid of ugly `python` title
* Fixes toolbar rendering on OSX (at least for now)
* Adds `SignalPanelRowLabel` for ease of styling
Closes #260 
Before (OSX/Win32):
After (OSX/Win32):
> FIX: font sizes in pixels, window title, and OSX toolbar

- .travis.yml
- dev-requirements.txt
- run_tests.py
- tests/test_benchmark.py
- tests/test_cache.py
- tests/test_cli.py
- typhos/app.py
- typhos/benchmark/cases.py
- typhos/benchmark/device.py
- typhos/benchmark/profile.py
- typhos/benchmark/utils.py
- typhos/cli.py
- typhos/suite.py
- typhos/utils.py
Adds a `benchmark` submodule and some `cli` tools to help us keep track of `typhos`'s performance.  This also required a refactor of the `cli` submodule to pull apart the large functions there.
Full feature checklist:
Some specific things to improve:
Remaining work before merging:
Stuff that I wanted to do but will not get to in this PR:
This was brought about because some of the larger screens have been taking a long time to load.
I've been testing locally, but this will be implicitly tested when I add the benchmark tests to the test suite.
I have not yet documented anything beyond docstrings.
> ENH: Benchmarking Tools

- tests/test_plot.py
- typhos/tools/plot.py
(A bit heavy-handed of a solution to #307; closes #307 most likely)
Normally, the plot would automatically add all hinted signals to the plot tool as soon as it's added.
However, this appears to be a common source of segmentation faults on Travis CI.
> REF: do not automatically add hinted signals

- tests/test_cli.py
- typhos/cli.py
* Default name set to the classname, overridden with `[{'name': ...}]` syntax.
* Prefix by default will be `FAKE_PREFIX:` instead of just `FAKE`
* Closes #303 by not adding the device if loading fails
> FIX: non-importable devices from CLI arguments

- typhos/display.py
New qtpyinheritance dependency _should_ be picked up through new release pf pcdsutils, with this functionality 🤞
> REF: use less magical forward_property in favor of forward_properties

- typhos/cache.py
- typhos/display.py
Path cache was not previously cleared when the user clicked 'reload templates', meaning unless the cache was stale, it's possible nothing would happen.
Locally
> FIX: clear path cache when user clicks "reload templates"

- typhos/display.py
The widget (Display) has no sizeHint assigned to it. In this case here we set a suggested sizeHint to the widget size.
Closes #304
```
typhos ophyd.sim.SynAxis[] ophyd.sim.SynAxis["{'name':'foo'}"]
```
Before:
After:
```
typhos --fake-device pcdsdevices.device_types.BeckhoffAxis[]
```
Before:
After:
> FIX: Force sizeHint on widget with size as suggestion.

- typhos/display.py
- typhos/panel.py
* Remove display context menu in favor of configuration menu
* Add sections to context menus
Closes #322 
Config drop-down menu:
Panel context menu:
> REF: remove display context menu; add sections to other menus

- tests/test_display.py
- typhos/app.py
- typhos/display.py
- typhos/ui/PositionerBase.detailed.ui
- typhos/ui/detailed_screen.ui
- typhos/ui/engineering_screen.ui
Closes #320 
Closes #319 
Adds back some OSX fixes lost in a rebase, and removes border for the scroll area.
Previews for a BeckhoffAxis, made large enough to not show the vertical scrollbar:
Embedded positioner
-----------------------
Detailed screen
----------------
Detailed positioner
--------------------
Engineering
---------------
Tree does not change.
> REF: rework default templates (misc panel removal; add normal panel)

- typhos/panel.py
Take a sit as this one is going to be hard to believe...
@klauer and I chased the damn ghost widgets for a while in the past and it looked like it was because of multiple calls to the creation of the widgets.
After noticing them back when switching templates or refreshing templates via the display settings menu I decided to go after this hunt again.
- Start a SimDetector
- typhos ophyd.areadetector.SimDetector['{"name":"camera", "prefix":"13SIM1:"}']
- Click at the Display Settings... and select Refresh Templates.
- Notice now the ghost widgets appearing without label or readback.
Interestingly, this does not happen with a Fake device:
- typhos --fake ophyd.areadetector.SimDetector['{"name":"camera", "prefix":"13SIM1:"}']
While testing I was being lead to believe that it was due to the …
> FIX: Adjust comparison to check for None instead of general check.

- typhos/ui/style.qss
- typhos/utils.py
Add a `LOADING_TIMEOUT_MS` and `enable_timeout` options at `TyphosLoading` widget.
Closes https://github.com/pcdshub/typhos/issues/258
Locally
Docstrings
> ENH: Drop loading gif after a certain timeout.

- typhos/display.py
Borrowed from pydm. Ensures that adl2pydm displays that have no layout are actually displayed.
> FIX: fix display size for widgets with no layout or minimum size

- tests/test_positioner.py
- typhos/positioner.py
Use current position, velocity, and acceleration signals to pick a motion timeout value of an appropriate size.
Slow moving motors hit a default timeout of 10s at some point in the call stack. This raises the `WaitTimeout` error in the screen, confusing users. This is a straightforward way to define a timeout that is "high enough" to not trip unless there is a problem.
I haven't tested this yet
Docstrings only
> MNT: positioner widget set timeouts

- typhos/positioner.py
If something goes wrong in the determination of the timeout, let the user know but do not stop the move.
The timeout determination isn't strictly necessary for the screen to start motion. The user should know that something has gone wrong, but should not be penalized by a non-move.
> MNT: contingency for error in selecting timeout

- docs/source/conf.py
- docs/source/widgets.rst
- tests/variety_ioc.py
- typhos/cache.py
- typhos/display.py
- typhos/panel.py
- typhos/textedit.py
- typhos/tweakable.py
- typhos/ui/tweakable.ui
- typhos/utils.py
- typhos/variety.py
- typhos/widgets.py
Variety metadata adds the possibility for distinguishing different types of signals from one another.
These different varieties of signals map differently onto typhos widgets.
This PR adds the framework and outlines examples for handling all of the currently defined varieties (pairing with https://github.com/pcdshub/pcdsdevices/pull/463)
While this adds a considerable amount of magic by way of decorators, I believe the sheer number of metadata keys, varieties, and classes justifies this. These additional decorators also allow for automatic annotation of class docstrings for documentation generation and such.
Note: For signals without variety designation (99.995% of them currently), this PR should have no effect.
Almost entirely locally. This could be considered an experimental feature. …
> Variety metadata + test IOC

- dev-requirements.txt
- docs/source/conf.py
BLD: Add doctr-versions-menu to dev-requirements.txt.
This morning while looking to the nice new feature to show someone how we use versioned docs with GitHub Pages I was surprised that I could not see it as I could at the `testproject1234` (See https://hhslepicka.github.io/testproject1234/master/).
Comparing both, I noticed that we need to add the `doctr-versions-menu` extension at the conf.py for docs.
It is a Draft for now as it depends on https://github.com/conda-forge/staged-recipes/pull/12250 to be merged and available via Conda-forge.
To properly render the versioned docs.
It is documentation.
> DOC: Add doctr_versions_menu extension to properly render version menu.

- typhos/display.py
Addresses my latter portion of #354 
It'd be better to not delete the previous widget until the 2nd widget is successfully loaded, but that can be a refactor down the line.
> FIX: widget unboundlocalerror

- typhos/positioner.py
Skip the first put to the combobox
See #383. We're currently putting to signals on startup which can be very disruptive.
It doesn't raise an exception on startup any more. The state device still moves on the first combobox selection action.
> MNT: work around init bug

- typhos/widgets.py
Closes #386 
Did not dive into the source of it, but this appears to stop the exception.
> FIX: set self._channel to avoid AttributeError

- typhos/ui/devices/AttenuatorCalculator_AT2L0.detailed.ui
- typhos/ui/devices/AttenuatorCalculator_AT2L0.ui
- typhos/ui/devices/AttenuatorCalculator_AT2L0_calc.ui
- typhos/ui/devices/AttenuatorCalculator_AT2L0_filters.ui
- typhos/ui/devices/AttenuatorCalculator_AT2L0_overview.ui
- typhos/ui/devices/AttenuatorCalculator_filter.ui
- typhos/ui/devices/at2l0_filters.json
Add screens for LCLS's HXR solid attenuator AT2L0.
For external collaborators that may be looking in, these LCLS-specific screens will not be here permanently.
However, they are named in such a way that even if they were, they should not affect operation in your facility.
These screens make it painfully obvious that our style sheet needs fixing.
Basic screen:
Detailed screen includes the basic screen plus some read-only information:
Filter configuration customization (material, thickness) is done on the auto-generated device screen.
> UI: add attenuator calculator screens

- typhos/widgets.py
Closes #369 
Plus some `isort`-related spam
Inadvertently changing setpoints while scrolling through screens is not a good thing.
Locally.
> FIX: do not change setpoints when QComboBox is scrolled

- .pre-commit-config.yaml
- typhos/panel.py
- typhos/utils.py
Closes #355
It's impossible with the current master to determine which PVs are failing to connect.
Locally.
Adds a tooltip, in case the PV itself is rather long:
Also adds a context menu for easy copy/paste-ability:
Copy either a single line or the entire tooltip to the clipboard.
This is a bit lacking in terms of UX discoverability, but I think it's a reasonable trade-off to weird reflowing issues we'd get listing the PVs in the timeout message. Agree?
> ENH: add information to the loading widget indicating timeout details

- typhos/widgets.py
Closes #382
Command buttons and their readback are poorly represented in auto-generated typhos screens.
This takes one small step in the direction of rectifying that - see the screenshots for details.
Before:
After:
> MNT: show byte indicator as readback for "command"; default button text

- docs/source/release_notes.rst
See title. We haven't tagged typhos in ages.
> DOC: v1.1.0 release notes

- typhos/benchmark/utils.py
In whatever pytest version is being used in the pcds-envs tests, some phantom modules are created in the tests submodule that we attempt to import inside the profiler, but this fails. The PR here just skips the ghost modules.
pcds-envs tests fail
python run_tests.py before and after the change
> MNT: skip bad module names from pytest + isort

- typhos/ui/devices/AttenuatorCalculator_AT2L0_calc.ui
User commented that the confirmation dialog is unnecessary due to the fact that there are several steps required to apply the configuration - this PR removes that confirmation dialog.
With https://github.com/pcdshub/solid-attenuator/pull/56, floor and ceiling calculations are no longer supported. These may be removed in future screens, but will be left in for now.
Closes #409 
Locally with a simulated AT2L0.
> MNT: remove confirmation to move AT2L0 filters as requested (LCLS-II/PCDS device screens)

- typhos/ui/devices/AttenuatorCalculatorSXR_Blade.embedded.ui
- typhos/ui/devices/AttenuatorCalculatorSXR_FourBlade.detailed.ui
- typhos/ui/devices/AttenuatorCalculatorSXR_FourBlade.ui
- typhos/ui/devices/AttenuatorCalculatorSXR_FourBlade_calc.ui
- typhos/ui/devices/AttenuatorCalculatorSXR_FourBlade_filters.ui
- typhos/ui/devices/AttenuatorCalculatorSXR_FourBlade_overview.ui
Screens for AT1K4 and similar.
* We still do not have a separate device screen repository.  (**Is it time?** I'd be OK with closing this and moving these elsewhere.)
* The attenuators do not generate very useful screens and benefit greatly from custom ones.
Interactively, with typhos and a simulation IOC.
> ENH: add AttenuatorCalculatorSXR for AT1K4 et al

- dev-requirements.txt
Set ipython version to the highest on conda forge that exists for python 3.6 in hopes of fixing the docs CI
Note: we should consider moving our docs builds to 3.8 or even 3.9
Docs builds started failing because the ipython sphinx extension has a bug in a random old build, and that build gets picked with high priority whenever it is allowed for some reason.
The CI is the test, but I created a bunch of environments offline
This is docs
> CI: Fix docs build

- typhos/panel.py
signal_name_to_info changed during iteration:
```
[2021-02-22 09:43:35] - ERROR - Unable to add 'at1k4' to TyphosSuite
Traceback (most recent call last):
File "/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/typhos/suite.py", line 511, in from_devices
suite.show_subdisplay(device)
File "/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/typhos/suite.py", line 307, in show_subdisplay
widget = self.get_subdisplay(widget)
File "/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/typhos/suite.py", line 288, in get_subdisplay
subdisplay = subdisplay()
File "/reg/g/pcds/pyps/conda/py36/envs/pcds-4.0.0/lib/python3.8/site-packages/typhos/display.py", line 1093, in from_device
display.add_device(device, macros=macros)
File …
```
> FIX: signal_name_to_info changed during iteration

- MANIFEST.in
The lack of the JSON file causes some really strange issues with PyDM (so we think, so far).
Need to look into more details.
Closes #429 
If the conda build works, this should be OK
> FIX: manifest fix for UI JSON files and happi test utils

- README.md
- dev-requirements.txt
Remove codecov. We aren't using it and they had a security breach
> MNT: remove codecov following security breach

- typhos/cli.py
Simple addition of a sigint handler.
... and requisite isort cleanup.
While rapidly developing and hitting ctrl-c to exit quickly, typhos crashing causes macOS to show an annoying modal window.
Interactively.
> ENH: add SIGINT/Ctrl-C handler

- docs/source/basic_usage.rst
- typhos/designer.py
- typhos/display.py
- typhos/utils.py
A sketch of a help widget, with the start of confluence integration.
Assumes environment variables are set appropriately:
* `TYPHOS_HELP_URL` (confluence, in our case)
* `TYPHOS_HELP_HEADERS` JSON headers for the help get request
* `TYPHOS_HELP_TOKEN` Shorthand for specifying bearer authorization in the get request without the JSON above (we have a general user with read-only access now; access via token not shared password)
Notes:
* If `TYPHOS_HELP_URL` is unset, this feature is a no-op compared to master. You won't see the `?` button even. 
* Confluence tokens are only on dev confluence for now. Not sure when it'll be updated on production.
Initial step toward closing #114 
Interactively.
> ENH: help widget

- docs/source/basic_usage.rst
- typhos/display.py
- typhos/jira.py
- typhos/utils.py
Prerequisite PR: #443 (code is based on it)
* Add an easy way for users to report issues with devices/user interfaces/etc
* Configured using environment variables, as in the help widget
All locally.
See included documentation.
> ENH: add Jira bug report dialog [LCLSPC-32]

- docs/source/templates.rst
- typhos/positioner.py
Remove the option to set stop to None
Require stop to raise AttributeError to remove the button
Get it in before the v2.0.0 tag
In the last tag: the stop button would appear no matter what, so this won't be an API break except on master.
Bluesky logs at the exception level if a call to stop() fails, as it should.
The API here for typhos should not encourage anyone to get into that state.
It's also really messy to override a function with None.
Interactively
Need to add a docs page suggesting how to override with attribute error
> MNT: hide stop only on attribute error to avoid bluesky trap

- typhos/cache.py
- typhos/widgets.py
Enum strings may change - or be clarified - during the life of a signal in typhos.
Signals in which we override the EPICS-level enum strings with more descriptive values at the Python layer are a feature of https://github.com/pcdshub/pcdsdevices/pull/899. This PR allows for those customized strings to be used.
Updated enum string information provided by ophyd signals is currently ignored.
Pairs with https://github.com/pcdshub/pcdsdevices/pull/899
Interactively.
See linked PR for implementation details.
> ENH/FIX: respect ophyd signal enum_strs and metadata updates

- typhos/widgets.py
Typhos supports two paths to get data from ophyd Signals.
1. Peeking into the `EpicsSignal` to see which PVs it is using and passing that along to PyDM
2. Directly through the ophyd subscription mechanism
This PR allows for an escape hatch for (1) in scenarios where we want typhos to use method (2).
This escape hatch comes in the form of a control layer `cl` check to see if the user has customized it beyond what ophyd supports.
Related to https://github.com/pcdshub/atef/pull/17
Where we want archived data to be sourced rather than live data
Interactively, so far
This PR text.
This is a typhos screen using this PR that gets data from the EPICS archiver:
> REF: direct-to-PV vs signal protocol by way of cl

- typhos/app.py
- typhos/cli.py
- typhos/display.py
- typhos/suite.py
- typhos/ui/devices/PositionerBase.embedded.ui
Add the following options to the CLI and their corresponding handlers in the library:
- `--layout`: pick between horizontal (default), vertical, grid, or flow layouts. The flow layout is lifted from PyDM and allows the user to resize the window and have the widgets populate the space as needed, e.g. a semi-dynamic grid.
- `--cols`: select how many columns the grid layout has
- `--display-type`: pick between embedded, detailed (default), or engineering screen as the kind of display to open at the start.
- `--scrollable`: pick between auto (default), true, and false to control whether the screen can have scrollbars or not. While auto is the default, this is actually new behavior: allows scrollbars for detailed and engineering screens, but not for embedded screens.
- `--size`: pick a …
> ENH: add suite options for layouts, display types, scrollbars, and starting window size

- .travis.yml
- typhos/benchmark/utils.py
- typhos/tests/conftest.py
- typhos/tests/test_cli.py
- Fix the CI to run two tests that were accidentally skipped
- Bring the `set.add` call into the `TypeError` try/except block that is intended to catch us trying to add an unhashable type to the set.
- Make the application handling in test_cli more consistent to avoid a hanging test suite
I don't know why this was working before or is failing now. The new object that passed the first check and made it to the add method was a `dict[str, str]`
Two tests were failing silently because there were accidentally skipped.
Unit tests pass, change seems innocuous
Will be in the release notes
> MNT: fix newly found failure in get_native_methods

- typhos/positioner.py
- typhos/widgets.py
Follow-up to #389 
Copy that fix over to the combo boxes used for the positioner widget so that when you scroll over the motor destination you don't accidentally trigger a move, e.g. if you are scrolling up and down a long screen.
This causes unintended moves which can and do lead to lost beam time.
Locally with no write access to the real PVs, comparing before and after the patch.
N/A
> BUG: fix issue where combobox positioners can dangerously trigger moves via mousewheel

- typhos/cli.py
- typhos/suite.py
Add `--hide-displays` option to open a typhos suite with all displays hidden.
If there are too many devices, the typhos suite is hard to use when everything opens immediately.
Interactively only.
Not yet
> ENH: add option to hide displays in suite at start

- typhos/positioner.py
- typhos/utils.py
`_write_pv` and `_read_pv` are generally good assumptions for `EpicsSignalBase` and its subclasses. However, typhos should be lenient if/when access to these attributes fails.
pcdsdevices may also require adjustments to `PytmcSignalRO`, but that shouldn't affect this PR.
Closes #474 
Closes #473 
Test suite and interactively with problematic `PytmcSignalRO` signal.
Issue and PR text.
> FIX: write pv assumption

- typhos/display.py
- typhos/plugins/core.py
- typhos/suite.py
- typhos/tests/conftest.py
- typhos/tests/plugins/test_core.py
- typhos/tests/test_display.py
- typhos/tests/test_positioner.py
- typhos/tests/utils/sig.ui
Register a device's signals when it is added to a `TyphosDeviceDisplay` so that device templates can include channels like `sig://${name}.setpoint` that refer to named signals on the device.
Fix a bug where suites could not find subdisplays for certain devices with underscores in their names in certain situations.
We need to make typhos templates easier to construct from device definitions and more flexible for non-EPICS devices.
Added some tests
Needs interactive testing before merge
Not yet
> Allow use of sig:// protocol in typhos templates

- typhos/alarm.py
- typhos/utils.py
Simply ignore this error when it pops up.
For background on why this happens, see https://github.com/slaclab/pydm/issues/798
If we do fix how the cleanup happens here, this PR is still needed because it's possible for a race condition to hit this line at a bad time anyway.
I snuck a side change in about setting up the devices list earlier because it helped me in the debugging process by fixing some of the reprs during the initial load.
closes #470 
Interactively only
It'll be in the release notes
> BUG: Workaround for C++ Wrapped Exception

- typhos/display.py
- typhos/tests/variety_ioc.py
* Currently, for a screen like at2l0's calculator under its `detailed_tree` display, the configuration menu is defunct
* Clicking the configuration menu does not result in any behavior
* With this change, the menu displays correctly
Fixes long-standing bug for custom screens.
Interactively.
This PR text.
> FIX: show templates even for non-signal panel displays

- typhos/tools/console.py
Adding an ophyd device declared outside of a module to typhos triggers an exception along with a traceback. With @klauer's guidance, I changed the logging method to `error` to suppress the traceback.
I was attempting to run the Getting Started code with my own device that talks to pydm's testing IOC (see https://github.com/slaclab/pydm-examples). The generated display loaded successfully but many errors were spewed.
My test code:
```py
import sys
from ophyd import Device, Component, EpicsSignal
from qtpy.QtWidgets import QApplication
import typhos
class MTest(Device):
"""
Test device from pydm-testing-ioc
"""
run = Component(EpicsSignal, 'Run')
my_device = MTest('MTEST:', name='my_device', read_attrs=['run'])
app = QApplication.instance() or QApplication(sys.argv)
typhos.use_stylesheet() …
```
> Log "Unable to add device..." as an error instead of an exception

- typhos/tests/test_cli.py
I wrapped the body of `test_cli_stylesheet` in a try/finally block to ensure that test.qss is cleaned up when the test is completed, pass or fail.
Addresses https://github.com/pcdshub/typhos/issues/428
If `test_cli_stylesheet` fails, the line `os.remove('test.qss') is never executed. Therefore, test.qss is left behind.
```py
def test_cli_stylesheet(qapp, qtbot, happi_cfg):
with open('test.qss', 'w+') as handle:
handle.write(
"TyphosDeviceDisplay {qproperty-force_template: 'test.ui'}")
style = qapp.styleSheet()
window = typhos_cli(['test_motor', '--stylesheet', 'test.qss',
'--happi-cfg', happi_cfg])
qtbot.addWidget(window)
suite = window.centralWidget()
dev_display = suite.get_subdisplay(suite.devices[0])
assert dev_display.force_template == 'test.ui'
qapp.setStyleSheet(style) …
```
> Ensure that test.qss is deleted regardless of CLI stylesheet test result

- .gitignore
- typhos/ui/widgets/positioner.ui
This changes the sizing strategy of the positioner widget from what was essentially fixed-width sizing to minimum size and expanding. This fixes cases where the positioner widget looked scrunched up or otherwise clipping.
It was reported in RIX that large numbers in the limits fields (in this case, 12 visible digits) would get clipped at the ends when rendered on the 4K high-dpi displays in the control room.
Interactively only- need to run on the RIX control room machines to fully confirm.
Just this PR
I don't have a high-dpi monitor at my desk, so to simulate and test this I would set the font side of the limits fields that were clipping on the control room display from 8pt to 50pt to guarantee clipping.
Here is what it looked like before:
And after:
> BUG: Fix Positioner clipping

- typhos/display.py
- typhos/utils.py
* Only show relevant help items when TYPHOS_HELP_URL is set
* Otherwise, show docstring-related information as it's still potentially useful
Closes #452
Interactively
Issue + PR text
> FIX: show python documentation when no web help is available

- typhos/suite.py
Initial attempt at fixing the suite sidebar
The device tree isn't really visible, presumably due to either typhos refactoring or pyqtgraph changes relating to Qt sizing/layouts.
I think this isn't the correct solution, but it'll work as a temporary solution as I investigate further.
This also doesn't affect the overlay not being sized properly (when hovering over the popbar but not pinning it). That remains broken as of the first commit.
> FIX: suite side popbar width

- typhos/cli.py
- typhos/display.py
- typhos/suite.py
* All suite tools are now lazily loaded
* Miscellaneous performance fixes as I found that:
* We call `load_best_template` twice (due to a setattr in a property and then an explicit call)
* We call `setVisible` on displays and then move them into a new layout - effectively doing a show/hide/show event under the hood
* Preliminary results indicate a pretty big speed-up, but I'd like to run more tests before making any claims about percentages
* Speed is important
* Tools are rarely used but heavy
* Interactively
* TODO: based on another branch because I was trying to fix that and lazily did not check out master again
This PR text
> REF: lazy load all tools and hopefully improve performance

- typhos/benchmark/utils.py
Currently, `@classmethod` annotated class methods are not picked up in the profiling tools.
This fix includes them in the profiler output.
I noticed the cached path tooling wasn't working as expected.
Locally
```
$ typhos --profile-modules typhos pydm at2l0_calc
```
This PR text
> FIX: profile classmethods as well

- typhos/display.py
`_get_specific_screens` was using the non-cached paths, duplicating the effort of the cached path mechanism.
Hopefully address speed a bit more on slow network filesystems
Locally
This PR text
> FIX: use cached paths for finding class templates

- typhos/tests/plugins/test_core.py
Removes deprecated and annoying `.value` access in test suite for ophyd
Pulled out of #491 to isolate its issues
Test suite
This PR text
> TST: fix ophyd signal value deprecation warning

- .travis.yml
- typhos/cache.py
- typhos/suite.py
- typhos/tests/test_benchmark.py
- typhos/utils.py
* Add cleanup for background threads
* Add replacement for `functools.partial` usage in methods as this was causing TyphosSuite from getting garbage collected
* Dangling cache daemon threads appear to cause a segfault on pip-installed PyQt5 but not conda-forge PyQt5
* I tried the signal `QApplication.aboutToQuit` instead of `atexit`, thinking it'd be better to clean up when the QApplication does. I found that the slot wasn't getting called and fell back to `atexit`.
* The garbage collection issue led to the test suite failing in a very strange way:
*  The benchmarks in `test_benchmark` are configured to run and create very nested device displays. These device displays were supposed to get garbage collected between tests, but they were not. 
* Once the test suite reached `test_cli`, typhos …
> FIX: atexit hook to clean up cache threads, TyphosSuite garbage collection

- typhos/func.py
- typhos/positioner.py
Set parent=self for each of the uses of `TyphosStatusThread`
I don't think these thread objects get cleaned up properly due to being orphaned, so this might cause weird on-shutdown behavior that interferes with e.g. the `lightpath` test suite. It's not really clear though.
N/A
Kind of just hoping the unit tests still pass
N/A
> MNT: add parents for internal uses of TyphosStatusThread

- typhos/panel.py
- Do not wait for lazy signals when creating a `SignalPanel`
Found in working with lightpath that devices with area detectors would wait for every signal to time out when creating a detailed screen. https://github.com/pcdshub/lightpath/issues/161
The issue could be solved by enforcing no_lazy_wait_for_connection at device creation, but this catches devices regardless of how they were created
Works in lightpath interactively. 
Test suite passed locally, but severely slowed the typing of this pr text
This PR text.
> BUG: do not wait for lazy connections in SignalPanel

- dev-requirements.txt
- typhos/positioner.py
- typhos/tests/test_positioner.py
Add the `alarmKindLevel` on `PositionerWidget` to configure the embedded alarm widget's `kindLevel` in designer.
I noticed in one of my screens that I wanted to adjust this knob and it wasn't available.
This is a configurable that decides how many signals are checked for the alarm status. The default value remains as before: keep all ophyd signals at "normal" level and higher. If you want to include fewer or additional signals in the alarm summary this will help you do that.
Added tests + verified interactively
Release notes only
> ENH: add designer property for configuring positioner alarm circle

- typhos/positioner.py
- typhos/tests/test_positioner.py
Use the status text to report errors that were encountered in calling move/set.
These are currently uncaught and then bubble up to become a pop-up message via the normal pydm mechanisms.
This is usually sufficient except:
- the error gets in your way and then you close it and then it's gone
- there are inconsistencies in where the error pop-up appears. For example, on my SLAC setup it appears between my two monitors, with half the text on the 4K monitor and the other half on the laptop screen.
I added a unit test and tested interactively using some EPICS test motors
It will be in the release notes
> ENH: use the status text to report move/set errors

- docs/source/basic_usage.rst
- typhos/cli.py
- typhos/tests/test_utils.py
- typhos/tests/utils/big_stylesheet.qss
- typhos/tests/utils/tiny_stylesheet.qss
- typhos/utils.py
- Include the normal stylesheets that load when `pydm` loads.
- Re-implement the stylesheet loading and composition rather than using `pydm`'s utilities to enforce a specific order.
- Include a way to add a stylesheet in CLI instead of the previous version which only had a way to override all stylesheets.
closes #540
Added a test, tested interactively with the case I cared about
Docstrings, comments, and sphinx docs updating.
Later: release notes
> FIX: include pydm and user pydm stylesheets

- docs/source/upcoming_release_notes/558-fix_py310_benchmark.rst
- typhos/benchmark/utils.py
Fix an issue where the cli benchmark package walk could discover an anaconda tests module in addition to the expected typhos submodules.
I noticed that our python 3.10 integration tests started failing for typhos with nonsensical import errors like typhos.tests.conda_env. It turns out that we were picking up site-packages/tests in the package walk starting from typhos:
<details>
```
In [3]: import typhos, pkgutil
In [4]: list(pkgutil.walk_packages(typhos.__path__))
Out[4]:
[ModuleInfo(module_finder=FileFinder('/cds/home/z/zlentz/github/typhos/typhos'), name='__main__', ispkg=False),
ModuleInfo(module_finder=FileFinder('/cds/home/z/zlentz/github/typhos/typhos'), name='alarm', ispkg=False),
ModuleInfo(module_finder=FileFinder('/cds/home/z/zlentz/github/typhos/typhos'), name='app', …
```
> FIX: ignore bonus unrelated modules found in py310 walk

- conda-recipe/meta.yaml
- requirements.txt
- typhos/display.py
- typhos/notes.py
- typhos/tests/test_notes.py
- typhos/tests/utils/env_device_notes.yaml
- typhos/tests/utils/user_device_notes.yaml
- typhos/utils.py
One proposal for how one might add descriptions to devices.
Searches in the following places for a device notes yaml:
1. `<user_data_path>/device_notes.yaml`
2. `PCDS_DEVICE_NOTES` environment variable
The above list is also the priority ranking, where higher priority sources shadow/overwrite lower priority information.  (aka if both of the above exist, information from `DEVICE_NOTES` will take precedence).  In general more local information will shadow more global information
If nothing exists, we default to the user_data_path, where we also write new note information 
All of this is up for debate and subject to change.
https://jira.slac.stanford.edu/browse/ECS-1039 , but also dovetailing off of https://github.com/pcdshub/lucid/pull/124
interactively, opening typhos and lucid
this PR.
> ENH: add notes field in TyphosDisplayTitle

- docs/source/upcoming_release_notes/566-screenshot.rst
- typhos/cli.py
- typhos/display.py
- typhos/suite.py
- typhos/tests/test_suite.py
- typhos/tests/test_utils.py
- typhos/utils.py
Add `typhos --screenshot filename_pattern` to take screenshots of typhos displays prior to exiting early (in combination with `--exit-after`).
Larger changes to layouts coming in #563 
We should check screenshots from the current master and compare them with #563 to ensure that the latter is strictly an improvement
Test suite and interactively
This PR text and pre-release notes
```
$ typhos --fake-device ophyd.EpicsMotor[] --screenshot "{device.name}.png" --exit-after 1
[2023-08-09 09:40:41] - WARNING - Exiting typhos early due to --exit-after=1.0 CLI argument.
[2023-08-09 09:40:41] - INFO - Saving screenshot of 'Typhos Suite - EpicsMotor': 'EpicsMotor' to 'EpicsMotor.png'
```
> ENH: add `--screenshot` to the typhos CLI

- docs/source/upcoming_release_notes/565-poslimits.rst
- typhos/positioner.py
* `obj.limits` can be `(None, None)` in some (perhaps?) disconnected/misconfigured devices.
* These limits may not have an associated component, and may be derived directly from the control layer (i.e., EPICS CA PV low/high limits)
* This PR detects the presence of `None` and *currently* hides the limits
For discussion: on connection, it's possible those limits could go to an actual not-`None` value. In that scenario, this PR would have already hidden the limit widgets and they would not be displayed later. 
Aims to close #565
With the "all device screenshot test" mentioned in side channels
Issue and PR text
> FIX: patch over positioner `limits = (None, None)` issue

- docs/source/upcoming_release_notes/570-dynamic_fonts.rst
- typhos/dynamic_font.py
- typhos/positioner.py
- typhos/tests/test_dynamic_font.py
- typhos/widgets.py
* Based on tests in https://github.com/pcdshub/qtpy-dynamic-font-size-label (thanks to https://github.com/jonaias/DynamicFontSizeWidgets) this adds a monkeypatching tool for widgets which have fonts and contain text
* Using this method, the widget size in the layout then determines how big the widget will be and therefore how big the font will be
* It seems viable, though should be used sparingly as it has the potential to impact performance
* Added padding option to the original proof-of-concept
New embedded positioner screens in #563 - @ZLLentz was aiming to have positioner readback values display in large form uniformly on all displays.
A bit interactively and with the included unit test.
It'd be a good idea to do more interactive testing, I think.
I also updated our [upstream test …
> ENH: dynamic font resizing functionality

- docs/source/upcoming_release_notes/571-width_resizing.rst
- typhos/display.py
- typhos/suite.py
- typhos/tests/test_suite.py
Automatically resize the typhos suite width when initially loaded or when a new template is loaded.
* Horizontal scroll bars are annoying when loading up a new suite
* Aiming to alleviate that by better specifying minimum size hints and growing free-floating suites when new templates are selected
Interactively and with a small included test
This PR text
> ENH/FIX: display resizing when new templates are shown

- docs/source/upcoming_release_notes/582-enh_positioner_timeout_scale.rst
- typhos/positioner.py
Increase the motion timeout times proportionally for longer moves, to decrease the chances of a false positive.
There were some complaints from MFX that their motors were timing out early.
Prior to this PR, the motion timeouts were:
- Minimum 5 second (settle_time)
- otherwise, slightly greater than the expected travel time (distance/speed + 2*acceleration time)
In some cases for longer moves, the expected time to get to the goal would be wrong by greater than 5 seconds.
This makes it so that these cases are less likely to frivolously error without compromising faster timeout feedback for the shorter moves. I toyed with increasing the base settle time from 5 to, say, 10, but that doesn't help these long moves enough and it delays the timeout message for motors that are expected to arrive …
> ENH: positioner timeout scaling

- typhos/positioner.py
- typhos/ui/widgets/positioner_row.ui
Adds TyphosDisplaySwitcher to row positioner widget.
This only required changes to the .ui file, to my complete amazement.  👏 
closes #580 in this case, but not the general one.
Clicking through all the other templates available to me, and I never got stuck
This PR
> MNT: add TyphosDisplaySwitcher to positioner_row.ui

- .github/PULL_REQUEST_TEMPLATE.md
- docs/source/upcoming_release_notes/588-doc_checklist_prnotes.rst
- Adds PR Checklist to PR Template
- adds pre-release notes for #587 
I forgor and didn't want to again
N/A
This PR
> DOC: add checklist to Pull Request Template

- docs/source/upcoming_release_notes/585-fix_positioner_setpoint.rst
- typhos/positioner.py
- typhos/ui/widgets/positioner.ui
Fixes an issue where the setpoint widgets for the detailed views were coming up with zero width.
The root cause of the issue was that the sizing of the user_setpoint placeholder widget was set to the defaults, so the `setMinimumWidth` call was setting the minimum width of the combobox to 0.
The reason why these various widgets refuse to expand here despite having their size policy set to "Expanding" eludes me, so I've set them to fixed with.
This also incidentally combines some previously diverging code paths that fixes a sizing issue where the detailed view had a vestigial/unused pydm line edit taking up space.
closes #585 
Interactively only
I need to make a release notes docs entry
Master:
This PR:
> FIX: make setpoint work for original positioner widget, adjust sizing

- docs/source/upcoming_release_notes/592-fix_signal_prec_default.rst
- pyproject.toml
- typhos/plugins/core.py
- typhos/tests/plugins/test_core.py
When the core (signal) plugin receives a floating point value with no precision information or nonsensical precision information, set the precision metadata to a sensible default.
Manual precision setting at the device/signal level is still supported fully.
By default, we had/have the following cases:
Before:
`0.23` displays as `0`
After:
`0.23` displays as `0.230`
I added targeted unit tests
Works interactively with state_velo, which is the signal that led us to this issue:
Release notes
> FIX: signal prec default

- docs/source/upcoming_release_notes/595-maint_cli_defaults.rst
- typhos/cli.py
- typhos/tests/test_cli.py
When launching a typhos suite via the CLI, set the default look/feel to the embedded/vertical mode.
In recent months we've revamped the most-used embedded templates (motors) to be row widgets, which give a much better screen in general if stacked vertically.
In the past prior to these changes, there was already clamoring for embedded as the default for screen space saving (closes #532)
Interactively only
Motors open up in neat row-by-row line widgets
Larger devices (somehow?) open up as they always have (TODO investigate)
Only here
> MAINT: switch typhos cli defaults to embedded/vertical by popular demand

- typhos/plugins/core.py
- typhos/tests/plugins/test_core.py
In the __init__ method of `typhos.core.SignalConnection` class, it looks up the signal corresponding to its address in the signal_registry dictionary. This PR adds an optional ``signal=None`` argument to the SignalConnection.__init__() method. If *signal* is ``None`` (default), then the behavior is the same as before. However, if a *signal* is provided, it will be used for the rest of the connection.
This makes the SignalConnection class more flexible, and allows it to be used with other registries. In my case, I want to look up signals from the [ophyd-registry package](https://pypi.org/project/ophyd-registry/) since the dictionary style registry used by Typhos doesn't meet all my use-cases. To do that, I will subclass the ``SignalConnection`` and ``SignalPlugin`` classes.
In its current …
> Added an optional signal parameters to SignalConnection.__init__

- docs/source/upcoming_release_notes/600-enh_lim_colors.rst
- typhos/ui/widgets/positioner.ui
- typhos/ui/widgets/positioner_row.ui
Switch the limit indicator colors to something more visible for the positioner widgets.
Many justified complaints about yellow -> brighter yellow being impossible to see for many users/screens
Interactively only
slack thread, so far, release notes later
old:
new:
> ENH: switch lim colors to blk/org from yel/yel

- .gitignore
- docs/source/index.rst
- docs/source/unit_tests.rst
- docs/source/upcoming_release_notes/607-tst_fix_ci_saga.rst
- pytest.ini
- typhos/positioner.py
- typhos/tests/conftest.py
- typhos/tests/test_benchmark.py
- typhos/tests/test_positioner.py
- typhos/tests/test_widgets.py
This PR resolves the following CI issues:
- The CI fails for Python 3.10+ if QT_QPA_PLATFORM=offscreen with a segmentation fault.
- There was an additional failure related to pyqtgraph changes that resulted in the per-test widget cleanup assert failing for the singular test that creates a pyqtgraph widget. This affected only the conda builds...
The PR fixes these largely by adding a `no_gc` pytest mark that skips the `gc.collect()` call that causes some of the tests to have a segmentation fault and a `no_cleanup_check` mark that skips the post-test cleanup assert.
In short: skip these in the cases where they don't work.
The other changes here are:
- Ignore .vscode config
- Skip benchmark tests by default, because they are long-running and tend to leak into other parts of the test suite.
- …
> CI/TST: Fix CI

- .gitignore
- docs/source/upcoming_release_notes/604-perf_resize_text.rst
- typhos/dynamic_font.py
- typhos/tests/test_dynamic_font.py
Move the dynamic text resizing to resize event so it doesn't happen every frame and use the entire cpu
https://jira.slac.stanford.edu/browse/ECS-5143
Interactively to observe the usage
Tests slightly adjusted so they still pass (previously was looking for the paint event)
Here and in release notes
> PERF: set text size on resize event, not on paint event, to avoid 100% cpu

- docs/source/upcoming_release_notes/606-enh_wait_status.rst
- typhos/func.py
- typhos/positioner.py
- typhos/status.py
- typhos/tests/test_positioner.py
- typhos/tests/test_status.py
- typhos/ui/widgets/positioner_row.ui
- Refactor TyphosStatusThread to give clearer and more detailed information (may count as API break)
- Change status thread behavior: thread timeout doesn't count as a failure, thread will continue to watch status until it eventually succeeds or fails.
- Adjust timeout messages to be more friendly (a positioner widget timeout doesn't mean your system is broken)
- Adjust timeout messages to disappear once a successful move completes
- More consistently pass through status failure exception messages to the positioner widget
- Give more detailed information about the timeout when it occurs
- Some motors in prod here are timing out and scaring/confusing people consistently
- There are always lots of questions about what the timeout is or where it comes from
- …
> ENH: improved wait status and positioner timeout messages

- docs/source/upcoming_release_notes/611-enh_positioner_resizing.rst
- typhos/dynamic_font.py
- typhos/panel.py
- typhos/positioner.py
- typhos/tests/test_dynamic_font.py
- typhos/ui/devices/PositionerBase.embedded.ui
- typhos/ui/widgets/positioner.ui
- typhos/ui/widgets/positioner_row.ui
Rework the design, sizing, and font scaling of the positioner row widget to address concerns about readability in RIX for devices with large position numbers, and to address issues with poorly used space in state devices.
- Allow dynamic font scaling to be applied to comboboxes
- Allow dynamic font resizing widgets to optionally define a minimum and maximum font size.
- Let font size change by less than the delta if it is to snap to the minimum or maximum, making sizing more consistent at the edges.
- Minor caching optimizations related to dynamic font scaling (there could be more improvements here) 
- setText-based widgets with dynamic font scaling now also adjust their font size when their text contents change
- Remove sizing overrides for dynamic patched widgets because they are no …
> ENH: positioner row widget sizing usability fixes and tweaks

- conda-recipe/meta.yaml
- dev-requirements.txt
- docs/source/upcoming_release_notes/615-maint_fix_ci.rst
pin pcdsdevices to latest in tests to avoid older versions being picked
the github actions on the merge of #611 failed because of some environment changes in the python ecosystem related to numpy 2.0
this is tests
I'll add a pre-release notes
> BLD: pin pcdsdevices to try to fix CI

- docs/source/upcoming_release_notes/616-fix_enum_handling.rst
- typhos/plugins/core.py
- typhos/tests/plugins/test_core.py
Fix three issues related to enum/metadata handling in the `SignalConnection` part of the `SignalPlugin` and implement simplified unit tests for these cases.
- Switch the order of the metadata/value setup for new listeners to ensure widgets have the correct contextual information. This is exactly the fix proposed by @canismarko in #605.
- Fix an issue where string=True enum EpicsSignals would reliably break on casting in cases where the enum strings were numerically the same as other indices in the enum_strs tuple. This builds upon the fix proposed by @canismarko in #608
- Fix a related (unreported) issue where the previous point could also break for string=False EpicsSignals.
closes #605 
closes #608 
Unit tests were added. I originally tried to make a larger unit test where I …
> FIX: metadata handling for enums

- dev-requirements.txt
- docs/source/upcoming_release_notes/618-bld_jinja_bump.rst
Unpin jinja, dependabot keeps sending me emails
leave my inbox alone
Let's see if the previously stated incompatibility with sphinx is still an issue
This PR
> BLD: unpin jinja, satiate dependabot

- conda-recipe/meta.yaml
- docs/source/upcoming_release_notes/620-fix_auto_scrollable.rst
- typhos/display.py
- typhos/suite.py
- typhos/tests/test_display.py
- Make scrollable=auto choose to include the scollbar or not based on the chosen template's display type. Previously, it was the selected type, even if that loaded a differently typed template. This means that "embedded" displays that open up large trees will now automatically be given scrollbars.
- Add some helpers to accomplish the above
- Add some tests to verify the above
- Switch display/suite defaults to match the cli defaults
closes #599 
as part of https://jira.slac.stanford.edu/browse/ECS-6333
I added some tests and ran some devices interactively.
Only here so far, and in the pre-release notes.
I was going to rewrite the cli help text but the original text more closely matches the new behavior than the old behavior.
```
parser.add_argument(
'--scrollable',
default='auto',
help=( …
```
> ENH/MNT/TST: make auto scrollable functional again

- docs/source/upcoming_release_notes/621-fix_combobox_resize_crash.rst
- typhos/dynamic_font.py
This is a hotfix we've been using for a while at LCLS.
It helps us avoid raising an exception the dynamic font rescaling function when it is applied to a combobox with no entries.
The normal logic flow here is to calculate the maximum allowable font size for each possible combobox entry, then take the minimum of these results so that any of the entries would fit in the combobox.
When there are no entries, we can't take the `min` of an empty list, leading to an exception.
Instead, the code will now exit since there's no reason to resize anything if there is no text.
This is an incomplete fix, the complete version would also include a dynamic resize when the combobox options are changed.
The reason this fix was never completed is that, after the IOC that caused this problem was fixed, we no …
> FIX: formalize hotfix for resizing empty comboboxes

- docs/source/upcoming_release_notes/622-fix_long_pos_msg_crash.rst
- typhos/positioner.py
- typhos/tests/test_positioner.py
- Fix an issue where the "text is too long" branch of the positioner widget's _set_status_text method would not work if the input was a string. There was an implementation error where we checked the input type but did not fully leverage it.
- Add a test for regression coverage.
- Tong ran into an issue today where an exception was being raised for what ended up being a limit error, but since the text for the limit error was very long it ended up triggering this bug.
Interactively via hotfix + here via unit test
Adding pre-release notes
> FIX: set message crash with long error message

- docs/source/upcoming_release_notes/625-fix_add_device_behavior_with_custom_displays.rst
- typhos/display.py
Make changes to _update_children to relink to a parent display so you can pass an ophyd.device to a custom pyqt screen. This allows you to run methods off the `.py` UIs and handle dynamic changes.
Both (upcoming `pcdsdevices`) `SmarAct.detailed.py` and `SmarActTipTilt.embedded.py` required accessing device information that _should've_ been added when `typhos` does it's magic, but would skip over the `display` without this change.
Very minimal change, testament to Zach's brevity. I tested this out on my custom displays in my `pcdsdevices` repo and it worked splendidly. 
This PR
> ENH: Zach's impressive 11 char fix to _update_children 

- docs/source/upcoming_release_notes/625-fix_add_device_behavior_with_custom_displays.rst
- docs/source/upcoming_release_notes/627-Add_long_name_for_SignalPanel.rst
- typhos/panel.py
Made changes to `SignalPanel` class  in `display` module to support `long_names` for device signals. This approach should be _pretty_ close to compatible with https://github.com/bluesky/ophyd/pull/1187, so if & when that comes through we should only need minimal changes.
Have you ever had a screen with 30+ signals and maybe multiple subcomponent devices with identical signal names?  Maybe you wanted alternative signal labels for cleaner GUI that end users can play with?
Figured some of the work I did in https://github.com/pcdshub/pcdsdevices/pull/1320 could be generalized in `typhos` and potentially trim the fat out of my screen scripts. 
Long names lets you use an optional string to replace the `label_text` in a `signal row` object added to your grid of signals. When you use a …
> Add long names

- .pre-commit-config.yaml
- docs/source/upcoming_release_notes/630-mnt_destroy.rst
- typhos/plugins/core.py
- typhos/tests/conftest.py
- Disconnect signals with `destroying=True` in the cleanup of our test suite channels/connections
- Pass around the `destroying` parameter to PyDMChannel's signal.disconnect methods for good measure (this didn't actually solve the issue)
Test suite was segfaulting, and I prematurely blamed pydm and attempted to pin.  Turns out there was something to do on our side. 
PyDM recently started passing around the `destroying` parameter and acting on it more thoroughly, and a knock on effect of this was a break in our tests.  I think it has to do with https://github.com/slaclab/pydm/pull/1218, but the end result was that we were trying to destroy a bunch of signals with `destroying=False`, while qt/qtbot had already deleted them.
In more verbose terms, the previous failure mode was:
```
.    >> …
```
> MNT: disconnect slots with destruction in mind
